repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

  # 1. High-entropy string detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  # 2. Scanning for specific cloud provider signatures
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        args: ["--config=.gitleaks.toml"]

  # 3. Standard Git "Sanity" Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^databrew-pipeline/
      - id: trailing-whitespace
        exclude: ^databrew-pipeline/
      - id: check-yaml
        args: ['--allow-multiple-documents']
        exclude: ^databrew-pipeline/
      - id: check-json
        exclude: ^databrew-pipeline/
