output "frontend_dns_challenge" {
  description = "Frontend ACME DNS record generated by Certificate Manager."
  value       = module.gateway_domain.frontend_dns_challenge
}

output "api_dns_challenge" {
  description = "API ACME DNS record generated by Certificate Manager."
  value       = module.gateway_domain.api_dns_challenge
}

output "frontend_certificate_state" {
  description = "Frontend certificate managed state."
  value       = module.gateway_domain.frontend_certificate_state
}

output "api_certificate_state" {
  description = "API certificate managed state."
  value       = module.gateway_domain.api_certificate_state
}
