# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-25T08:47:36+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, RootModel, constr


class ErrorResponse(BaseModel):
    code: str
    message: str
    request_id: str
    details: dict[str, Any] | None = None


class AssetID(
    RootModel[constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8)]
):
    root: constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8) = Field(
        ..., description='Primary key for assets (8 alphanumeric ASCII characters).'
    )


class RunID(
    RootModel[constr(pattern=r'^[0-9A-Za-z]{16}$', min_length=16, max_length=16)]
):
    root: constr(pattern=r'^[0-9A-Za-z]{16}$', min_length=16, max_length=16) = Field(
        ..., description='Primary key for algo_runs (16 alphanumeric ASCII characters).'
    )


class McapFileID(
    RootModel[constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8)]
):
    root: constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8) = Field(
        ..., description='Primary key for mcap_files (same format as asset_id).'
    )


class ActionID(
    RootModel[constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8)]
):
    root: constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8) = Field(
        ..., description='Primary key for actions (same format as asset_id).'
    )


class CustomerID(RootModel[str]):
    root: str = Field(..., description='Customer identifier (UUID or slug).')


class LifecycleState(Enum):
    created = 'created'
    processing = 'processing'
    ready = 'ready'
    delivered = 'delivered'
    archived = 'archived'
    superseded = 'superseded'
    failed = 'failed'
    rejected = 'rejected'


class Mcap(BaseModel):
    mcap_file_id: McapFileID | None = None
    mcap_uri: str | None = None
    size_bytes: int | None = None
    raw_hash_md5: str | None = None


class Window(BaseModel):
    start_timestamp_ns: int | None = None
    end_timestamp_ns: int | None = None
    duration_ms: int | None = None


class AssetMcapLocator(BaseModel):
    asset_id: AssetID | None = None
    lifecycle_state: str | None = None
    mcap: Mcap | None = None
    window: Window | None = None
    version: int | None = None
    updated_at: AwareDatetime | None = None


class FoxgloveSourceResponse(BaseModel):
    asset_id: AssetID | None = None
    source_id: str | None = None
    ds: str | None = None
    ds_params: dict[str, str] | None = None
    hints: dict[str, Any] | None = None
    expires_at: str | None = None


class LogicalAsset(BaseModel):
    logical_asset_id: str | None = None
    asset_type: str | None = None
    display_name: str | None = None
    description: str | None = None
    owner: str | None = None
    status: str | None = None
    current_revision: int | None = None
    total_revisions: int | None = None
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class CurrentAssetResponse(BaseModel):
    asset_id: AssetID | None = None
    revision: int | None = None
    logical_asset_id: str | None = None
    asset_type: str | None = None
    owner: str | None = None
    lifecycle_state: str | None = None


class RatingsHistoryMetric(BaseModel):
    metric_key: str | None = None
    metric_type: str | None = None
    metric_unit: str | None = None
    metric_value: float | None = None
    metric_value_int: int | None = None
    metric_value_text: str | None = None
    metric_value_bool: bool | None = None
    target_type: str | None = None
    target_id: str | None = None
    eval_name: str | None = None
    eval_version: str | None = None
    parameter_version: str | None = None
    run_id: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    confidence: float | None = None
    recorded_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class RatingsHistoryRevision(BaseModel):
    asset_id: AssetID | None = None
    revision: int | None = None
    is_current: bool | None = None
    lifecycle_state: str | None = None
    created_at: AwareDatetime | None = None
    ratings: list[RatingsHistoryMetric] | None = None


class RatingsHistoryResponse(BaseModel):
    logical_asset_id: str | None = None
    asset_type: str | None = None
    revisions: list[RatingsHistoryRevision] | None = None


class AssetTag(BaseModel):
    asset_id: AssetID | None = None
    tag_key: str | None = None
    tag_value: str | None = None
    tag_type: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None
    confidence: float | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    applied_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class TagUpsertRequest(BaseModel):
    tag_key: str | None = None
    tag_value: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None


class TagHistoryResponse(BaseModel):
    items: list[AssetTag] | None = None
    total: int | None = None


class AssetEvent(BaseModel):
    event_id: str | None = None
    event_seq: int | None = None
    event_type: str | None = None
    aggregate_type: str | None = None
    asset_id: AssetID | None = None
    mcap_file_id: str | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    event_source: str | None = None
    actor_type: str | None = None
    actor_id: str | None = None
    run_id: str | None = None
    event_payload: dict[str, Any] | None = None
    payload_schema_version: str | None = None
    publish_state: str | None = None
    created_at: AwareDatetime | None = None
    published_at: AwareDatetime | None = None
    occurred_at: AwareDatetime | None = None
    retry_count: int | None = None


class AssetEventListResponse(BaseModel):
    items: list[AssetEvent] | None = None
    limit: int | None = None
    next_cursor: int | None = None


class AssetEventSSEFrame(BaseModel):
    event_id: str | None = None
    event_seq: int | None = None
    event_type: str | None = None
    asset_id: AssetID | None = None
    event_payload: dict[str, Any] | None = None
    occurred_at: AwareDatetime | None = None


class Action(BaseModel):
    action_id: ActionID | None = None
    asset_id: AssetID | None = None
    start_ns: int | None = None
    end_ns: int | None = None
    action_index: int | None = None
    primary_label: str | None = None
    labels: list[str] | None = None
    description: str | None = None
    attrs: dict[str, Any] | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None
    confidence: float | None = None
    external_id: str | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    is_deleted: bool | None = None
    version: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class ActionCreateRequest(BaseModel):
    start_ns: int
    end_ns: int
    action_index: int | None = None
    primary_label: str | None = None
    labels: list[str] | None = None
    description: str | None = None
    attrs: dict[str, Any] | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None
    confidence: float | None = None
    external_id: str | None = None


class ActionPatchRequest(BaseModel):
    start_ns: int | None = None
    end_ns: int | None = None
    action_index: int | None = None
    primary_label: str | None = None
    labels: list[str] | None = None
    description: str | None = None
    attrs: dict[str, Any] | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None
    confidence: float | None = None
    expected_version: int | None = None


class ActionListResponse(BaseModel):
    items: list[Action] | None = None
    total: int | None = None


class Status(Enum):
    pending = 'pending'
    running = 'running'
    ok = 'ok'
    failed = 'failed'
    cancelled = 'cancelled'


class AlgoRun(BaseModel):
    run_id: RunID | None = None
    algo_name: str | None = None
    algo_version: str | None = None
    algo_kind: str | None = Field(
        None, description='e.g. seg_runner, clip_runner, eval'
    )
    triggered_by: str | None = Field(None, description='user_id or system')
    status: Status | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    duration_ns: int | None = None
    input_filter: dict[str, Any] | None = Field(
        None, description='Query IR filter used to select input assets.'
    )
    input_asset_ids: list[AssetID] | None = None
    params: dict[str, Any] | None = None
    code_commit: str | None = Field(None, description='Git commit SHA of algo code.')
    image_digest: str | None = Field(None, description='Container image digest used.')
    pipeline_name: str | None = None
    pipeline_version: str | None = None
    assets_processed: int | None = None
    assets_succeeded: int | None = None
    assets_failed: int | None = None
    actions_created: int | None = None
    metrics_written: int | None = None
    outputs: dict[str, Any] | None = None
    cpu_seconds: int | None = None
    gpu_seconds: int | None = None
    cost_usd_micros: int | None = None
    error_class: str | None = None
    error_message: str | None = None
    external_runtime: str | None = Field(
        None, description='External runtime identifier (e.g. dagster_run_id).'
    )
    external_url: str | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    row_version: int | None = None


class AlgoRunListResponse(BaseModel):
    items: list[AlgoRun] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class AlgoRunCreateRequest(BaseModel):
    algo_name: str | None = None
    algo_version: str | None = None
    algo_kind: str | None = None
    triggered_by: str | None = None
    params: dict[str, Any] | None = None
    input_filter: dict[str, Any] | None = None
    input_asset_ids: list[AssetID] | None = None


class AlgoRunStartRequest(BaseModel):
    code_commit: str | None = None
    image_digest: str | None = None
    pipeline_name: str | None = None
    pipeline_version: str | None = None


class Status1(Enum):
    ok = 'ok'
    failed = 'failed'


class AlgoRunFinishRequest(BaseModel):
    status: Status1 | None = None
    assets_processed: int | None = None
    assets_succeeded: int | None = None
    assets_failed: int | None = None
    actions_created: int | None = None
    metrics_written: int | None = None
    outputs: dict[str, Any] | None = None
    cpu_seconds: int | None = None
    gpu_seconds: int | None = None
    cost_usd_micros: int | None = None
    error_class: str | None = None
    error_message: str | None = None


class AlgoRunCancelRequest(BaseModel):
    reason: str


class AffectedAsset(BaseModel):
    asset_id: AssetID | None = None
    algo_status: str | None = None
    run_id: RunID | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class AlgoEvent(BaseModel):
    event_id: str | None = None
    asset_id: AssetID | None = None
    algo_key: str | None = None
    prev_status: str | None = None
    new_status: str | None = None
    run_id: str | None = None
    reason: str | None = None
    created_at: AwareDatetime | None = None


class AlgoEventListResponse(BaseModel):
    items: list[AlgoEvent] | None = None


class AlgoLifecycleResponse(BaseModel):
    key: str | None = None
    status: str | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    output_uri: str | None = None
    run_id: str | None = None
    reason: str | None = None


class StartAlgoRequest(BaseModel):
    method: str
    run_id: str | None = None


class FinishAlgoRequest(BaseModel):
    status: str
    output_uri: str | None = None
    run_id: str | None = None
    reason: str | None = None
    result_size_bytes: int | None = None
    extra_fields: dict[str, Any] | None = None


class Scope(BaseModel):
    resource: str | None = None
    include_history: bool | None = None


class FieldModel(BaseModel):
    name: str | None = None
    alias: str | None = None


class Select(BaseModel):
    fields: list[FieldModel] | None = None


class Condition(BaseModel):
    field: str | None = None
    operator: str | None = None
    value: Any | None = None


class Where(BaseModel):
    operator: str | None = None
    conditions: list[Condition] | None = None


class Order(Enum):
    asc = 'asc'
    desc = 'desc'


class SortItem(BaseModel):
    field: str | None = None
    order: Order | None = None


class Page(BaseModel):
    offset: int | None = None
    limit: int | None = None


class Facet(BaseModel):
    field: str | None = None
    size: int | None = None


class Debug(BaseModel):
    plan: bool | None = None


class QueryRequest(BaseModel):
    schema_version: str | None = None
    mode: str | None = None
    scope: Scope | None = None
    select: Select | None = None
    where: Where | None = None
    sort: list[SortItem] | None = None
    page: Page | None = None
    facets: list[Facet] | None = None
    debug: Debug | None = None


class ColumnDef(BaseModel):
    name: str | None = None
    type: str | None = None


class QueryRunResponse(BaseModel):
    items: list[dict[str, Any]] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None
    columns: list[str] | None = None
    column_defs: list[ColumnDef] | None = None
    offset: int | None = None
    limit: int | None = None
    facets: Any | None = None
    warnings: list[str] | None = None
    debug_plan: Any | None = None


class FieldCapability(BaseModel):
    field: str | None = None
    types: list[str] | None = None


class QueryValidateResponse(BaseModel):
    valid: bool | None = None
    normalized_query: Any | None = None
    warnings: list[str] | None = None
    field_capabilities: list[FieldCapability] | None = None
    debug_plan: Any | None = None


class SavedQuery(BaseModel):
    saved_query_id: str | None = None
    name: str | None = None
    description: str | None = None
    resource: str | None = None
    schema_version: str | None = None
    query_ir_json: QueryRequest | None = None
    owner: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class UpsertSavedQueryRequest(BaseModel):
    name: str
    description: str | None = None
    query_ir_json: QueryRequest | None = None
    owner: str | None = None


class Customer(BaseModel):
    customer_id: str | None = None
    display_name: str | None = None
    legal_name: str | None = None
    status: str | None = None
    region: str | None = None
    sla_tier: str | None = None
    account_owner: str | None = None
    compliance_tags: list[Any] | None = None
    exclude_tags: list[Any] | None = None
    metadata: dict[str, Any] | None = None
    extra: dict[str, Any] | None = None
    onboarded_at: AwareDatetime | None = None
    offboarded_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    row_version: int | None = None


class CustomerCreateRequest(BaseModel):
    customer_id: str
    display_name: str
    legal_name: str | None = None
    status: str | None = None
    region: str | None = None
    sla_tier: str | None = None
    account_owner: str | None = None
    compliance_tags: list[Any] | None = None
    exclude_tags: list[Any] | None = None
    metadata: dict[str, Any] | None = None


class CustomerPatchRequest(BaseModel):
    display_name: str | None = None
    legal_name: str | None = None
    status: str | None = None
    region: str | None = None
    sla_tier: str | None = None
    account_owner: str | None = None
    compliance_tags: list[Any] | None = None
    exclude_tags: list[Any] | None = None
    metadata: dict[str, Any] | None = None


class CustomerListResponse(BaseModel):
    items: list[Customer] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class Status2(Enum):
    pending = 'pending'
    delivered = 'delivered'
    failed = 'failed'
    accepted = 'accepted'
    rejected = 'rejected'
    recalled = 'recalled'
    cancelled = 'cancelled'
    archived = 'archived'


class Delivery(BaseModel):
    delivery_id: str | None = None
    customer_id: str | None = None
    status: Status2 | None = None
    delivery_type: str | None = None
    note: str | None = None
    owner: str | None = None
    asset_count: int | None = None
    item_count: int | None = None
    contract_id: str | None = None
    manifest_uri: str | None = None
    replay_manifest_uri: str | None = None
    delivered_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None
    requested_by: str | None = None
    approved_by: str | None = None
    delivered_by: str | None = None
    total_size_bytes: int | None = None
    cancelled_at: AwareDatetime | None = None
    cancelled_by: str | None = None
    cancel_reason: str | None = None
    acknowledged_at: AwareDatetime | None = None
    acknowledged_by: str | None = None
    metadata: dict[str, Any] | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    version: int | None = None


class DeliveryListResponse(BaseModel):
    items: list[Delivery] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class DeliveryItem(BaseModel):
    delivery_id: str | None = None
    asset_id: AssetID | None = None
    created_at: AwareDatetime | None = None


class DeliveryItemsResponse(BaseModel):
    items: list[DeliveryItem] | None = None
    total: int | None = None


class DeliveryDraftRequest(BaseModel):
    customer_id: str
    asset_ids: list[AssetID] | None = None
    contract_id: str | None = None
    note: str | None = None
    owner: str | None = None


class DeliveryDraftResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class DeliveryAddItemsRequest(BaseModel):
    asset_ids: list[AssetID] = Field(..., min_length=1)


class DeliveryAddItemsResponse(BaseModel):
    added_count: int | None = None
    total_count: int | None = None


class DeliveryCommitRequest(BaseModel):
    asset_ids: list[AssetID] = Field(..., min_length=1)
    customer_id: str
    contract_id: str | None = None
    note: str | None = None
    owner: str | None = None


class DeliveryCommitResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class DeliveryCommitC2Request(BaseModel):
    expected_revision: int | None = None
    approved_by: str | None = None


class DeliveryCancelRequest(BaseModel):
    cancelled_by: str | None = None
    cancel_reason: str | None = None


class DeliveryCancelResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class DeliveryRetryResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class DeliveryAckRequest(BaseModel):
    acknowledged_by: str | None = None


class DeliveryAckResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class CustomerDeliveryIDsResponse(BaseModel):
    delivery_ids: list[str] | None = None


class DeliveryRule(BaseModel):
    rule_id: UUID | None = None
    name: str | None = None
    owner: str | None = None
    customer_id: str | None = None
    query_dsl: Any | None = None
    dsl_version: str | None = None
    enforce_mode: str | None = None
    rating_scope: str | None = None
    is_active: bool | None = None
    version: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class DeliveryRuleCreateRequest(BaseModel):
    name: str
    owner: str
    customer_id: str | None = None
    query_dsl: Any
    dsl_version: str | None = None
    enforce_mode: str | None = None
    rating_scope: str | None = None
    is_active: bool | None = None


class DeliveryRuleListResponse(BaseModel):
    items: list[DeliveryRule] | None = None


class DeliveryRuleViolation(BaseModel):
    rule_id: str | None = None
    rule_name: str | None = None
    asset_id: AssetID | None = None
    violation: str | None = None
    severity: str | None = None


class IngestState(Enum):
    pending = 'pending'
    summarized = 'summarized'
    failed = 'failed'


class McapFile(BaseModel):
    mcap_file_id: McapFileID | None = None
    gcs_path: str | None = None
    size_bytes: int | None = None
    raw_hash_md5: str | None = None
    raw_hash_sha256: str | None = None
    ingest_state: IngestState | None = None
    file_duration_ms: int | None = None
    start_timestamp_ns: int | None = None
    end_timestamp_ns: int | None = None
    channel_count: int | None = None
    chunk_count: int | None = None
    vendor_id: str | None = None
    collector_id: str | None = None
    task_id: str | None = None
    device_id: str | None = None
    camera_model: str | None = None
    data_source: str | None = None
    location_id: str | None = None
    scene_id: str | None = None
    environment_id: str | None = None
    collection_method: str | None = None
    owner: str | None = None
    retention_tier: str | None = None
    expire_at: AwareDatetime | None = None
    metadata: dict[str, Any] | None = None
    process_state: dict[str, str] | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    version: int | None = None


class McapFileListResponse(BaseModel):
    items: list[McapFile] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class McapCreateFileRequest(BaseModel):
    mcap_file_id: str | None = None
    gcs_path: str | None = None
    mcap_uri: str | None = None
    size_bytes: int | None = None
    raw_hash_md5: str | None = None
    raw_hash_sha256: str | None = None
    ingest_state: str | None = None
    file_duration_ms: int | None = None
    start_timestamp_ns: int | None = None
    end_timestamp_ns: int | None = None
    channel_count: int | None = None
    chunk_count: int | None = None
    vendor_id: str | None = None
    collector_id: str | None = None
    task_id: str | None = None
    device_id: str | None = None
    camera_model: str | None = None
    data_source: str | None = None
    location_id: str | None = None
    scene_id: str | None = None
    environment_id: str | None = None
    collection_method: str | None = None
    owner: str | None = None
    retention_tier: str | None = None
    expire_at: AwareDatetime | None = None
    metadata: dict[str, Any] | None = None
    process_state: dict[str, str] | None = None
    tenant_id: str | None = None
    project_id: str | None = None


class McapFinalizeUploadRequest(BaseModel):
    mcap_file_id: str


class EvalResult(BaseModel):
    eval_result_id: str | None = None
    target_type: str | None = None
    target_id: str | None = None
    eval_name: str | None = None
    eval_version: str | None = None
    parameter_version: str | None = None
    run_id: str | None = None
    status: str | None = None
    result_payload: dict[str, Any] | None = None
    output_uri: str | None = None
    summary_uri: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class EvalResultRequest(BaseModel):
    target_type: str | None = None
    target_id: str | None = None
    eval_name: str
    eval_version: str
    parameter_version: str | None = None
    run_id: str | None = None
    status: str | None = None
    result_payload: dict[str, Any] | None = None
    output_uri: str | None = None
    summary_uri: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None


class EvalResultListResponse(BaseModel):
    items: list[EvalResult] | None = None
    total: int | None = None


class MetricEntry(BaseModel):
    metric_key: str | None = None
    metric_value: float | None = None
    metric_value_int: int | None = None
    metric_value_text: str | None = None
    metric_value_bool: bool | None = None
    metric_type: str | None = None
    eval_name: str | None = None
    eval_version: str | None = None
    run_id: str | None = None
    source_type: str | None = None
    recorded_at: AwareDatetime | None = None


class MetricListResponse(BaseModel):
    items: list[MetricEntry] | None = None


class Op(Enum):
    eq = 'eq'
    gt = 'gt'
    gte = 'gte'
    lt = 'lt'
    lte = 'lte'


class Metric(BaseModel):
    metric_key: str
    op: Op
    value: float | None = None


class Filters(BaseModel):
    lifecycle_state: str | None = None
    metrics: list[Metric] | None = None


class SearchByMetricsRequest(BaseModel):
    filters: Filters | None = None
    page: int | None = None
    page_size: int | None = None


class Item(BaseModel):
    key: str | None = None
    display_name: str | None = None
    metric_type: str | None = None
    metric_unit: str | None = None
    target_type: str | None = None
    higher_is_better: bool | None = None
    default_aggregation: str | None = None
    queryable: bool | None = None
    description: str | None = None


class MetricsRegistryResponse(BaseModel):
    items: list[Item] | None = None


class AlgoRegistryItem(BaseModel):
    key: str | None = None
    name: str | None = None
    version: str | None = None
    depends_on: list[str] | None = None


class TagRegistryItem(BaseModel):
    key: str | None = None
    description: str | None = None
    type: str | None = None
    values: list[str] | None = None
    max_length: int | None = None


class LifecycleState1(BaseModel):
    state: str | None = None


class SyncInfo(BaseModel):
    elasticsearch_ok: bool | None = None
    outbox_relay_enabled: bool | None = None
    outbox_es_subscriber_enabled: bool | None = None
    search_index_mode: str | None = None
    env: str | None = None
    admin_search_enabled: bool | None = None


class SyncProgress(BaseModel):
    postgres_assets_total: int | None = None
    elasticsearch_docs_total: int | None = None
    pg_es_gap: int | None = None
    pg_es_sync_ratio: float | None = None
    outbox_pending_events: int | None = None
    outbox_pending_claimable: int | None = None
    outbox_processing_events: int | None = None
    outbox_relay_safety_lag_sec: int | None = None
    oldest_pending_age_sec: int | None = None
    pg_max_event_seq: int | None = None
    outbox_published_max_seq: int | None = None
    seq_lag: int | None = None
    es_applied_min_seq: int | None = None
    consumer_lag: int | None = None
    checked_at: AwareDatetime | None = None


class LakehouseReport(BaseModel):
    total_assets: int | None = None
    total_deliveries: int | None = None
    total_customers: int | None = None
    total_mcap_files: int | None = None
    generated_at: AwareDatetime | None = None


class LakehouseStatus(BaseModel):
    healthy: bool | None = None
    enabled: bool | None = None
    backend: str | None = None
    project: str | None = None
    dataset: str | None = None


class LakehouseTableCount(BaseModel):
    table_name: str | None = None
    row_count: int | None = None


class LakehouseTableListResponse(BaseModel):
    items: list[LakehouseTableCount] | None = None


class LakehouseOverviewResponse(BaseModel):
    active_assets: int | None = None
    asset_total: int | None = None
    bronze_event_rows: int | None = None
    data_lag_hours: float | None = None
    day7_avg_new_assets: float | None = None
    mcap_total: int | None = None
    today_new_assets: int | None = None
    week_new_assets: int | None = None


class LakehouseEventDailyItem(BaseModel):
    event_date: date_aliased | None = None
    event_count: int | None = None


class LakehouseEventDailyResponse(BaseModel):
    items: list[LakehouseEventDailyItem] | None = None


class LakehouseAssetGrowthItem(BaseModel):
    date: date_aliased | None = None
    cumulative: int | None = None
    daily_delta: int | None = None


class LakehouseAssetGrowthResponse(BaseModel):
    items: list[LakehouseAssetGrowthItem] | None = None


class Item1(BaseModel):
    key: str | None = None
    count: int | None = None


class LakehouseItemsResponse(BaseModel):
    type_stats: Any | None = None
    items: list[Item1] | None = None


class FailureClusterItem(BaseModel):
    failure_mode: str | None = None
    algo_name: str | None = None
    affected_assets: int | None = None
    ratio: float | None = None


class BronzeSyncProgress(BaseModel):
    outbox_published_max_seq: int | None = None
    bronze_max_event_seq: int | None = None
    bronze_lag_events: int | None = None
    bronze_last_ingested_at: AwareDatetime | None = None
    bronze_stale_seconds: float | None = None
    checked_at: AwareDatetime | None = None


class SyncStatusData(BaseModel):
    dagster_run_id: str | None = None
    checked_at: AwareDatetime | None = None
    pg_total_count: int | None = None
    iceberg_total_count: int | None = None
    count_diff_pct: float | None = None
    pg_status_dist: Any | None = None
    iceberg_status_dist: Any | None = None
    status_diff: Any | None = None
    is_alert: bool | None = None
    iceberg_max_seq: int | None = None


class SyncStatusResponse(BaseModel):
    available: bool | None = None
    source: str | None = None
    message: str | None = None
    data: SyncStatusData | None = None


class AuditEventRow(BaseModel):
    event_id: str | None = None
    event_seq: int | None = None
    event_type: str | None = None
    aggregate_type: str | None = None
    asset_id: AssetID | None = None
    mcap_file_id: str | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    event_source: str | None = None
    actor_type: str | None = None
    actor_id: str | None = None
    run_id: str | None = None
    occurred_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class AuditSearchResponse(BaseModel):
    items: list[AuditEventRow] | None = None
    total: int | None = None
    next_cursor: str | None = None


class LineageNode(BaseModel):
    asset_id: AssetID | None = None
    parent_asset_id: str | None = None
    child_asset_id: str | None = None
    relation_type: str | None = None
    direction: str | None = None
    depth: int | None = None
    method: str | None = None
    algo_name: str | None = None
    algo_version: str | None = None
    run_id: str | None = None
    created_at: AwareDatetime | None = None


class LineageSearchResponse(BaseModel):
    nodes: list[LineageNode] | None = None


class LineageResponse(BaseModel):
    asset_id: AssetID | None = None
    upstream: Any | None = None
    downstream: Any | None = None


class ProvenanceEntry(BaseModel):
    source_asset_id: AssetID | None = None
    relation_type: str | None = None
    method: str | None = None
    algo_name: str | None = None
    run_id: str | None = None
    created_at: AwareDatetime | None = None


class AssetProvenanceResponse(BaseModel):
    asset_id: AssetID | None = None
    root_asset_id: AssetID | None = None
    provenance: list[ProvenanceEntry] | None = None


class SearchReindexRequest(BaseModel):
    dry_run: bool | None = None
    page_size: int | None = None


class SearchReindexResponse(BaseModel):
    dry_run: bool | None = None
    total_assets: int | None = None
    indexed: int | None = None
    deleted: int | None = None
    failed: int | None = None
    duration_ms: int | None = None
    errors: list[str] | None = None
    elasticsearch_doc_count: int | None = None
    assets_scanned: int | None = None
    documents_indexed: int | None = None
    documents_deleted: int | None = None


class SearchReindexJobView(BaseModel):
    id: str | None = None
    job_type: str | None = None
    status: str | None = None
    progress_n: int | None = None
    progress_of: int | None = None
    error_detail: str | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class SearchReindexJobsListResponse(BaseModel):
    items: list[SearchReindexJobView] | None = None


class SearchOutboxStatsResponse(BaseModel):
    publish_state_counts: dict[str, int] | None = None
    outbox_dlq_rows: int | None = None


class SearchAuditResponse(BaseModel):
    pg_assets: int | None = None
    elasticsearch_docs: int | None = None
    missing_in_elasticsearch: int | None = None
    orphan_in_elasticsearch: int | None = None
    consistency: float | None = None
    target: float | None = None
    sample_missing_ids: list[str] | None = None
    sample_orphan_ids: list[str] | None = None
    duration_ms: int | None = None


class BatchDeleteRequest(BaseModel):
    asset_ids: list[AssetID] | None = None
    import_batch: str | None = None
    include_mcap_files: bool | None = None
    dry_run: bool | None = None
    chunk_size: int | None = None


class BatchDeleteResponse(BaseModel):
    deleted_count: int | None = None
    dry_run: bool | None = None


class Segment(BaseModel):
    start_ns: int | None = None
    end_ns: int | None = None
    asset_type: str | None = None
    metadata: dict[str, Any] | None = None


class InternalCommitSegmentsRequest(BaseModel):
    mcap_file_id: McapFileID | None = None
    segments: list[Segment] | None = None


class LoginRequest(BaseModel):
    token: str


class LoginResponse(BaseModel):
    authenticated: bool | None = None


class Asset(BaseModel):
    asset_id: AssetID | None = None
    mcap_file_id: McapFileID | None = None
    segment_locator: str | None = Field(
        None, description='Deterministic SHA-1 of mcap_file_id + start_ns + end_ns'
    )
    start_timestamp_ns: int | None = None
    end_timestamp_ns: int | None = None
    duration_sec: float | None = Field(
        None, description='Legacy: duration in seconds (backward compat)'
    )
    duration_ms: int | None = None
    lifecycle_state: LifecycleState | None = None
    asset_type: str | None = Field(
        None, description='Asset type (e.g. segment, clip, frame_set, derived_asset).'
    )
    status: str | None = Field(
        None,
        description='Legacy derived status (API-only, not stored). One of: approved, rejected, archived, superseded.',
    )
    owner: str | None = None
    reviewer: str | None = None
    type: str | None = Field(None, description='Legacy: mirrors asset_type.')
    retention_tier: str | None = None
    expire_at: AwareDatetime | None = None
    storage_uri: str | None = None
    thumb_uri: str | None = None
    asset_level: int | None = None
    parent_asset_id: AssetID | None = None
    root_asset_id: AssetID | None = None
    split_method: str | None = None
    split_algo_name: str | None = None
    split_algo_version: str | None = None
    split_run_id: str | None = None
    split_reason: str | None = None
    segment_index: int | None = None
    parent_start_offset_ms: int | None = None
    parent_end_offset_ms: int | None = None
    delivery_count: int | None = None
    last_delivered_at: AwareDatetime | None = None
    last_delivered_to: str | None = None
    env: str | None = None
    task: str | None = None
    version: int | None = None
    algo_results: dict[str, str] | None = None
    tags: dict[str, str] | None = Field(
        None,
        description='Flat key→value map (last-write-wins). For multi-source use tags_detailed.',
    )
    tags_detailed: list[AssetTag] | None = None
    files: dict[str, str] | None = None
    files_json: dict[str, Any] | None = Field(
        None, description='JSONB alternative to files.'
    )
    algo_inputs_uris: dict[str, str] | None = None
    annot_inputs_uris: dict[str, str] | None = None
    metadata: dict[str, Any] | None = None
    lifecycle_meta: dict[str, Any] | None = None
    logical_asset_id: str | None = None
    revision: int | None = None
    is_current: bool | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class AssetListResponse(BaseModel):
    items: list[Asset] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class DeliveryCommitC2Response(BaseModel):
    delivery_id: str | None = None
    status: str | None = None
    violations: list[DeliveryRuleViolation] | None = None
