# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
    conint,
    constr,
)


class ErrorResponse(BaseModel):
    code: str
    message: str
    request_id: str
    details: dict[str, Any] | None = None


class Source(Enum):
    argo_live = 'argo-live'


class Pagination(BaseModel):
    available: bool = Field(
        ...,
        description='Whether this log source can return another historical page through nextCursor.',
        examples=[False],
    )
    nextCursor: str = Field(
        ...,
        description='Cursor for the next historical window when available. Null for live Argo logs.',
    )
    reason: str | None = Field(
        None,
        examples=['live Argo logs do not provide stable historical cursor pagination'],
    )


class Mode(Enum):
    tail = 'tail'
    since = 'since'
    cursor = 'cursor'


class Window(BaseModel):
    mode: Mode = Field(..., examples=['tail'])
    tailLines: int | None = Field(None, examples=[200])
    limitBytes: int | None = Field(None, examples=[262144])
    sinceSeconds: int | None = None
    sinceTime: AwareDatetime | None = None
    previous: bool | None = None
    timestamps: bool | None = None
    scope: str = Field(..., examples=['bounded-live-window'])


class Truncation(BaseModel):
    bounded: bool = Field(..., examples=[True])
    tailLines: int = Field(..., examples=[200])
    maxTailLines: int = Field(..., examples=[2000])
    tailLinesClamped: bool | None = None
    limitBytes: int = Field(..., examples=[262144])
    maxLimitBytes: int = Field(..., examples=[2097152])
    limitBytesClamped: bool | None = None
    bytesTruncated: bool


class WorkflowLogResponse(BaseModel):
    workflowName: str
    nodeId: str
    podName: str
    container: str = Field(..., examples=['main'])
    source: Source
    logs: str
    lineCount: int
    truncated: bool = Field(
        ...,
        description='True when the server-side byte cap cut the returned log payload.',
    )
    nextCursor: str | None = Field(
        None,
        description='Always null; live Argo logs do not provide stable cursor pagination.',
    )
    pagination: Pagination
    window: Window
    truncation: Truncation


class ResourceValues(BaseModel):
    cpu: str | None = Field(None, examples=['500m'])
    memory: str | None = Field(None, examples=['256Mi'])


class Workflow(Enum):
    argo_live = 'argo-live'
    unavailable = 'unavailable'


class Metrics(Enum):
    unavailable = 'unavailable'


class Spec(Enum):
    stored_manifest = 'stored-manifest'
    unavailable = 'unavailable'


class ResourceUsageSource(BaseModel):
    workflow: Workflow = Field(
        ..., description='Source for workflow status and resource duration values.'
    )
    metrics: Metrics = Field(
        ...,
        description='Live Kubernetes Metrics API source; unavailable until metrics integration is wired.',
    )
    spec: Spec = Field(
        ..., description='Source for manifest-derived requests and limits.'
    )


class Pod(BaseModel):
    pod_name: str | None = None
    node_id: str | None = None
    node_name: str | None = None
    template_name: str | None = None
    observed_at: AwareDatetime | None = None
    live_metrics_available: bool | None = None
    requests: ResourceValues | None = None
    limits: ResourceValues | None = None
    resource_duration: ResourceValues | None = Field(
        None,
        description='Argo resource duration, not live CPU/memory usage or billing.',
    )
    cpu_usage: str | None = Field(
        None,
        description='Deprecated compatibility alias for cpu_resource_duration; not live CPU usage.',
    )
    memory_usage: str | None = Field(
        None,
        description='Deprecated compatibility alias for memory_resource_duration; not live memory usage.',
    )
    cpu_resource_duration: str | None = None
    memory_resource_duration: str | None = None
    cpu_request: str | None = None
    memory_request: str | None = None
    cpu_limit: str | None = None
    memory_limit: str | None = None


class ResourceUsageReport(BaseModel):
    deployment_id: str | None = None
    workflow_name: str
    status: str
    observed_at: AwareDatetime
    source: ResourceUsageSource
    live_metrics_available: bool = Field(
        ..., description='False when live CPU/memory samples are not available.'
    )
    pods: list[Pod]


class AssetID(
    RootModel[constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8)]
):
    root: constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8) = Field(
        ..., description='Primary key for assets (8 alphanumeric ASCII characters).'
    )


class RunID(
    RootModel[constr(pattern=r'^[0-9A-Za-z]{16}$', min_length=16, max_length=16)]
):
    root: constr(pattern=r'^[0-9A-Za-z]{16}$', min_length=16, max_length=16) = Field(
        ..., description='Primary key for algo_runs (16 alphanumeric ASCII characters).'
    )


class McapFileID(
    RootModel[constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8)]
):
    root: constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8) = Field(
        ..., description='Primary key for mcap_files (same format as asset_id).'
    )


class ActionID(
    RootModel[constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8)]
):
    root: constr(pattern=r'^[0-9A-Za-z]{8}$', min_length=8, max_length=8) = Field(
        ..., description='Primary key for actions (same format as asset_id).'
    )


class CustomerID(RootModel[str]):
    root: str = Field(..., description='Customer identifier (UUID or slug).')


class LifecycleState(Enum):
    created = 'created'
    processing = 'processing'
    ready = 'ready'
    delivered = 'delivered'
    archived = 'archived'
    superseded = 'superseded'
    failed = 'failed'
    rejected = 'rejected'


class AssetTypeSchema(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )


class Mcap(BaseModel):
    mcap_file_id: McapFileID | None = None
    mcap_uri: str | None = None
    size_bytes: int | None = None
    raw_hash_md5: str | None = None


class Window1(BaseModel):
    start_timestamp_ns: int | None = None
    end_timestamp_ns: int | None = None
    duration_ms: int | None = None


class AssetMcapLocator(BaseModel):
    asset_id: AssetID | None = None
    lifecycle_state: str | None = None
    mcap: Mcap | None = None
    window: Window1 | None = None
    version: int | None = None
    updated_at: AwareDatetime | None = None


class FoxgloveSourceResponse(BaseModel):
    asset_id: AssetID | None = None
    source_id: str | None = None
    ds: str | None = None
    ds_params: dict[str, str] | None = None
    hints: dict[str, Any] | None = None
    expires_at: str | None = None


class LogicalAsset(BaseModel):
    logical_asset_id: str | None = None
    asset_type: str | None = None
    display_name: str | None = None
    description: str | None = None
    owner: str | None = None
    status: str | None = None
    current_revision: int | None = None
    total_revisions: int | None = None
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class CurrentAssetResponse(BaseModel):
    asset_id: AssetID | None = None
    revision: int | None = None
    logical_asset_id: str | None = None
    asset_type: str | None = None
    owner: str | None = None
    lifecycle_state: str | None = None


class RatingsHistoryMetric(BaseModel):
    metric_key: str | None = None
    metric_type: str | None = None
    metric_unit: str | None = None
    metric_value: float | None = None
    metric_value_int: int | None = None
    metric_value_text: str | None = None
    metric_value_bool: bool | None = None
    target_type: str | None = None
    target_id: str | None = None
    eval_name: str | None = None
    eval_version: str | None = None
    parameter_version: str | None = None
    run_id: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    confidence: float | None = None
    recorded_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class RatingsHistoryRevision(BaseModel):
    asset_id: AssetID | None = None
    revision: int | None = None
    is_current: bool | None = None
    lifecycle_state: str | None = None
    created_at: AwareDatetime | None = None
    ratings: list[RatingsHistoryMetric] | None = None


class RatingsHistoryResponse(BaseModel):
    logical_asset_id: str | None = None
    asset_type: str | None = None
    revisions: list[RatingsHistoryRevision] | None = None


class AssetTag(BaseModel):
    asset_id: AssetID | None = None
    tag_key: str | None = None
    tag_value: str | None = None
    tag_type: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None
    confidence: float | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    applied_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class TagUpsertRequest(BaseModel):
    tag_key: str | None = None
    tag_value: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None


class TagHistoryResponse(BaseModel):
    items: list[AssetTag] | None = None
    total: int | None = None


class AssetEvent(BaseModel):
    event_id: str | None = None
    event_seq: int | None = None
    event_type: str | None = None
    aggregate_type: str | None = None
    asset_id: AssetID | None = None
    mcap_file_id: str | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    event_source: str | None = None
    actor_type: str | None = None
    actor_id: str | None = None
    run_id: str | None = None
    event_payload: dict[str, Any] | None = None
    payload_schema_version: str | None = None
    publish_state: str | None = None
    created_at: AwareDatetime | None = None
    published_at: AwareDatetime | None = None
    occurred_at: AwareDatetime | None = None
    retry_count: int | None = None


class AssetEventListResponse(BaseModel):
    items: list[AssetEvent] | None = None
    limit: int | None = None
    next_cursor: int | None = None


class AssetEventSSEFrame(BaseModel):
    event_id: str | None = None
    event_seq: int | None = None
    event_type: str | None = None
    asset_id: AssetID | None = None
    event_payload: dict[str, Any] | None = None
    occurred_at: AwareDatetime | None = None


class Action(BaseModel):
    action_id: ActionID | None = None
    asset_id: AssetID | None = None
    start_ns: int | None = None
    end_ns: int | None = None
    action_index: int | None = None
    primary_label: str | None = None
    labels: list[str] | None = None
    description: str | None = None
    attrs: dict[str, Any] | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None
    confidence: float | None = None
    external_id: str | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    is_deleted: bool | None = None
    version: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class ActionCreateRequest(BaseModel):
    start_ns: int
    end_ns: int
    action_index: int | None = None
    primary_label: str | None = None
    labels: list[str] | None = None
    description: str | None = None
    attrs: dict[str, Any] | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None
    confidence: float | None = None
    external_id: str | None = None


class ActionPatchRequest(BaseModel):
    start_ns: int | None = None
    end_ns: int | None = None
    action_index: int | None = None
    primary_label: str | None = None
    labels: list[str] | None = None
    description: str | None = None
    attrs: dict[str, Any] | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    run_id: str | None = None
    confidence: float | None = None
    expected_version: int | None = None


class ActionListResponse(BaseModel):
    items: list[Action] | None = None
    total: int | None = None


class Status(Enum):
    pending = 'pending'
    running = 'running'
    ok = 'ok'
    failed = 'failed'
    cancelled = 'cancelled'


class AlgoRun(BaseModel):
    run_id: RunID | None = None
    algo_name: str | None = None
    algo_version: str | None = None
    algo_kind: str | None = Field(
        None, description='e.g. seg_runner, clip_runner, eval'
    )
    triggered_by: str | None = Field(None, description='user_id or system')
    status: Status | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    duration_ns: int | None = None
    input_filter: dict[str, Any] | None = Field(
        None, description='Query IR filter used to select input assets.'
    )
    input_asset_ids: list[AssetID] | None = None
    params: dict[str, Any] | None = None
    code_commit: str | None = Field(None, description='Git commit SHA of algo code.')
    image_digest: str | None = Field(None, description='Container image digest used.')
    pipeline_name: str | None = None
    pipeline_version: str | None = None
    assets_processed: int | None = None
    assets_succeeded: int | None = None
    assets_failed: int | None = None
    actions_created: int | None = None
    metrics_written: int | None = None
    outputs: dict[str, Any] | None = None
    cpu_seconds: int | None = None
    gpu_seconds: int | None = None
    cost_usd_micros: int | None = None
    error_class: str | None = None
    error_message: str | None = None
    external_runtime: str | None = Field(
        None, description='External runtime identifier (e.g. dagster_run_id).'
    )
    external_url: str | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    row_version: int | None = None


class AlgoRunListResponse(BaseModel):
    items: list[AlgoRun] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class AlgoRunCreateRequest(BaseModel):
    algo_name: str | None = Field(None, examples=['scene-detector'])
    algo_version: str | None = Field(None, examples=['2.1.0'])
    algo_kind: str | None = Field(None, examples=['seg_runner'])
    triggered_by: str | None = Field(None, examples=['admin@cyberorigin.ai'])
    params: dict[str, Any] | None = Field(
        None, examples=[{'threshold': 0.85, 'max_scenes': 100}]
    )
    input_filter: dict[str, Any] | None = Field(
        None, examples=[{'asset_type': 'segment', 'lifecycle_state': 'ready'}]
    )
    input_asset_ids: list[AssetID] | None = Field(
        None,
        description='Optional explicit input asset IDs. Each ID must exist and must not be soft-deleted.',
        examples=[['a1b2c3d4', 'e5f6g7h8']],
    )


class AlgoRunStartRequest(BaseModel):
    code_commit: str | None = None
    image_digest: str | None = None
    pipeline_name: str | None = None
    pipeline_version: str | None = None


class Status1(Enum):
    ok = 'ok'
    failed = 'failed'


class AlgoRunFinishRequest(BaseModel):
    status: Status1 | None = None
    assets_processed: int | None = None
    assets_succeeded: int | None = None
    assets_failed: int | None = None
    actions_created: int | None = None
    metrics_written: int | None = None
    outputs: dict[str, Any] | None = None
    cpu_seconds: int | None = None
    gpu_seconds: int | None = None
    cost_usd_micros: int | None = None
    error_class: str | None = None
    error_message: str | None = None


class AlgoRunCancelRequest(BaseModel):
    reason: str


class AffectedAsset(BaseModel):
    asset_id: AssetID | None = None
    algo_status: str | None = None
    run_id: RunID | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class AlgoEvent(BaseModel):
    event_id: str | None = None
    asset_id: AssetID | None = None
    algo_key: str | None = None
    prev_status: str | None = None
    new_status: str | None = None
    run_id: str | None = None
    reason: str | None = None
    created_at: AwareDatetime | None = None


class AlgoEventListResponse(BaseModel):
    items: list[AlgoEvent] | None = None


class AlgoLifecycleResponse(BaseModel):
    key: str | None = None
    status: str | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    output_uri: str | None = None
    run_id: str | None = None
    reason: str | None = None


class StartAlgoRequest(BaseModel):
    method: str
    run_id: str | None = None


class FinishAlgoRequest(BaseModel):
    status: str
    output_uri: str | None = None
    run_id: str | None = None
    reason: str | None = None
    result_size_bytes: int | None = None
    extra_fields: dict[str, Any] | None = None


class Scope(BaseModel):
    resource: str | None = None
    include_history: bool | None = None


class FieldModel(BaseModel):
    name: str | None = None
    alias: str | None = None


class Select(BaseModel):
    fields: list[FieldModel] | None = None


class Condition(BaseModel):
    field: str | None = None
    operator: str | None = None
    value: Any | None = None


class Where(BaseModel):
    operator: str | None = None
    conditions: list[Condition] | None = None


class Order(Enum):
    asc = 'asc'
    desc = 'desc'


class SortItem(BaseModel):
    field: str | None = None
    order: Order | None = None


class Page(BaseModel):
    offset: int | None = None
    limit: int | None = None


class Facet(BaseModel):
    field: str | None = None
    size: int | None = None


class Debug(BaseModel):
    plan: bool | None = None


class QueryRequest(BaseModel):
    schema_version: str | None = None
    mode: str | None = None
    scope: Scope | None = None
    select: Select | None = None
    where: Where | None = None
    sort: list[SortItem] | None = None
    page: Page | None = None
    facets: list[Facet] | None = None
    debug: Debug | None = None


class ColumnDef(BaseModel):
    name: str | None = None
    type: str | None = None


class QueryRunResponse(BaseModel):
    items: list[dict[str, Any]] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None
    columns: list[str] | None = None
    column_defs: list[ColumnDef] | None = None
    offset: int | None = None
    limit: int | None = None
    facets: Any | None = None
    warnings: list[str] | None = None
    debug_plan: Any | None = None


class FieldCapability(BaseModel):
    field: str | None = None
    types: list[str] | None = None


class QueryValidateResponse(BaseModel):
    valid: bool | None = None
    normalized_query: Any | None = None
    warnings: list[str] | None = None
    field_capabilities: list[FieldCapability] | None = None
    debug_plan: Any | None = None


class SavedQuery(BaseModel):
    saved_query_id: str | None = None
    name: str | None = None
    description: str | None = None
    resource: str | None = None
    schema_version: str | None = None
    query_ir_json: QueryRequest | None = None
    owner: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class UpsertSavedQueryRequest(BaseModel):
    name: str
    description: str | None = None
    query_ir_json: QueryRequest | None = None
    owner: str | None = None


class Customer(BaseModel):
    customer_id: str | None = None
    display_name: str | None = None
    legal_name: str | None = None
    status: str | None = None
    region: str | None = None
    sla_tier: str | None = None
    account_owner: str | None = None
    compliance_tags: list[Any] | None = None
    exclude_tags: list[Any] | None = None
    metadata: dict[str, Any] | None = None
    extra: dict[str, Any] | None = None
    onboarded_at: AwareDatetime | None = None
    offboarded_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    row_version: int | None = None


class CustomerCreateRequest(BaseModel):
    customer_id: str = Field(..., examples=['cust-acme-001'])
    display_name: str = Field(..., examples=['ACME Corporation'])
    legal_name: str | None = Field(None, examples=['ACME Technologies Ltd.'])
    status: str | None = Field(None, examples=['active'])
    region: str | None = Field(None, examples=['us-west1'])
    sla_tier: str | None = Field(None, examples=['premium'])
    account_owner: str | None = Field(None, examples=['zhangsan'])
    compliance_tags: list[Any] | None = None
    exclude_tags: list[Any] | None = None
    metadata: dict[str, Any] | None = None


class CustomerPatchRequest(BaseModel):
    display_name: str | None = None
    legal_name: str | None = None
    status: str | None = None
    region: str | None = None
    sla_tier: str | None = None
    account_owner: str | None = None
    compliance_tags: list[Any] | None = None
    exclude_tags: list[Any] | None = None
    metadata: dict[str, Any] | None = None


class CustomerListResponse(BaseModel):
    items: list[Customer] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class Status2(Enum):
    pending = 'pending'
    delivered = 'delivered'
    failed = 'failed'
    accepted = 'accepted'
    rejected = 'rejected'
    recalled = 'recalled'
    cancelled = 'cancelled'
    archived = 'archived'


class Delivery(BaseModel):
    delivery_id: str | None = None
    customer_id: str | None = None
    status: Status2 | None = None
    delivery_type: str | None = None
    note: str | None = None
    owner: str | None = None
    asset_count: int | None = None
    item_count: int | None = None
    contract_id: str | None = None
    manifest_uri: str | None = None
    replay_manifest_uri: str | None = None
    delivered_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None
    requested_by: str | None = None
    approved_by: str | None = None
    delivered_by: str | None = None
    total_size_bytes: int | None = None
    cancelled_at: AwareDatetime | None = None
    cancelled_by: str | None = None
    cancel_reason: str | None = None
    acknowledged_at: AwareDatetime | None = None
    acknowledged_by: str | None = None
    metadata: dict[str, Any] | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    version: int | None = None


class DeliveryListResponse(BaseModel):
    items: list[Delivery] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class DeliveryItem(BaseModel):
    delivery_id: str | None = None
    asset_id: AssetID | None = None
    created_at: AwareDatetime | None = None


class DeliveryItemsResponse(BaseModel):
    items: list[DeliveryItem] | None = None
    total: int | None = None


class DeliveryDraftRequest(BaseModel):
    customer_id: str = Field(..., examples=['cust-acme-001'])
    asset_ids: list[AssetID] | None = Field(None, examples=[['a1b2c3d4', 'e5f6g7h8']])
    contract_id: str | None = Field(None, examples=['contract-Q3-2024'])
    note: str | None = Field(None, examples=['Priority delivery for ACME Q3 batch'])
    owner: str | None = Field(None, examples=['zhangsan'])


class DeliveryDraftResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class DeliveryAddItemsRequest(BaseModel):
    asset_ids: list[AssetID] = Field(..., min_length=1)


class DeliveryAddItemsResponse(BaseModel):
    added_count: int | None = None
    total_count: int | None = None


class DeliveryCommitRequest(BaseModel):
    asset_ids: list[AssetID] = Field(
        ..., examples=[['a1b2c3d4', 'e5f6g7h8']], min_length=1
    )
    customer_id: str = Field(..., examples=['cust-acme-001'])
    contract_id: str | None = Field(None, examples=['contract-Q3-2024'])
    note: str | None = Field(None, examples=['Q3 release batch — customer ACME'])
    owner: str | None = Field(None, examples=['zhangsan'])


class DeliveryCommitResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class DeliveryCommitC2Request(BaseModel):
    expected_revision: int | None = None
    approved_by: str | None = None


class DeliveryCancelRequest(BaseModel):
    cancelled_by: str | None = Field(None, examples=['zhangsan'])
    cancel_reason: str | None = Field(
        None, examples=['Customer requested changes to asset list']
    )


class DeliveryCancelResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class DeliveryRetryResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class DeliveryAckRequest(BaseModel):
    acknowledged_by: str | None = Field(None, examples=['lisi'])


class DeliveryAckResponse(BaseModel):
    delivery_id: str | None = None
    status: str | None = None


class CustomerDeliveryIDsResponse(BaseModel):
    delivery_ids: list[str] | None = None


class DeliveryRule(BaseModel):
    rule_id: UUID | None = None
    name: str | None = None
    owner: str | None = None
    customer_id: str | None = None
    query_dsl: Any | None = None
    dsl_version: str | None = None
    enforce_mode: str | None = None
    rating_scope: str | None = None
    is_active: bool | None = None
    version: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class DeliveryRuleCreateRequest(BaseModel):
    name: str
    owner: str
    customer_id: str | None = None
    query_dsl: Any
    dsl_version: str | None = None
    enforce_mode: str | None = None
    rating_scope: str | None = None
    is_active: bool | None = None


class DeliveryRuleListResponse(BaseModel):
    items: list[DeliveryRule] | None = None


class DeliveryRuleViolation(BaseModel):
    rule_id: str | None = None
    rule_name: str | None = None
    asset_id: AssetID | None = None
    violation: str | None = None
    severity: str | None = None


class IngestState(Enum):
    pending = 'pending'
    summarized = 'summarized'
    failed = 'failed'


class McapFile(BaseModel):
    mcap_file_id: McapFileID | None = None
    gcs_path: str | None = None
    size_bytes: int | None = None
    raw_hash_md5: str | None = None
    raw_hash_sha256: str | None = None
    ingest_state: IngestState | None = None
    file_duration_ms: int | None = None
    start_timestamp_ns: int | None = None
    end_timestamp_ns: int | None = None
    channel_count: int | None = None
    chunk_count: int | None = None
    vendor_id: str | None = None
    collector_id: str | None = None
    task_id: str | None = None
    device_id: str | None = None
    camera_model: str | None = None
    data_source: str | None = None
    location_id: str | None = None
    scene_id: str | None = None
    environment_id: str | None = None
    collection_method: str | None = None
    owner: str | None = None
    retention_tier: str | None = None
    expire_at: AwareDatetime | None = None
    metadata: dict[str, Any] | None = None
    process_state: dict[str, str] | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    version: int | None = None


class McapFileListResponse(BaseModel):
    items: list[McapFile] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class McapCreateFileRequest(BaseModel):
    mcap_file_id: str | None = Field(
        None, description='8-character alphanumeric ID', examples=['mcap0012']
    )
    gcs_path: str | None = Field(
        None, examples=['gs://databrew-uploads/2024/03/run-001.mcap']
    )
    mcap_uri: str | None = Field(
        None, examples=['gs://databrew-uploads/2024/03/run-001.mcap']
    )
    size_bytes: int | None = Field(None, examples=[104857600])
    raw_hash_md5: str | None = Field(
        None, examples=['aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa']
    )
    raw_hash_sha256: str | None = Field(
        None,
        examples=['bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'],
    )
    ingest_state: str | None = Field(None, examples=['uploaded'])
    file_duration_ms: int | None = Field(None, examples=[3600000])
    start_timestamp_ns: int | None = Field(None, examples=[1700000000000000000])
    end_timestamp_ns: int | None = Field(None, examples=[1700003600000000000])
    channel_count: int | None = Field(None, examples=[8])
    chunk_count: int | None = Field(None, examples=[24])
    vendor_id: str | None = Field(None, examples=['acme-sensors'])
    collector_id: str | None = Field(None, examples=['vehicle-001'])
    task_id: str | None = Field(None, examples=['task-route-42'])
    device_id: str | None = Field(None, examples=['lidar-unit-03'])
    camera_model: str | None = Field(None, examples=['FLIR-BFS-U3-16S2'])
    data_source: str | None = Field(None, examples=['onboard-recording'])
    location_id: str | None = Field(None, examples=['loc-sf-downtown'])
    scene_id: str | None = Field(None, examples=['scene-heavy-traffic'])
    environment_id: str | None = Field(None, examples=['env-urban-day'])
    collection_method: str | None = Field(None, examples=['automatic'])
    owner: str | None = Field(None, examples=['zhangsan'])
    retention_tier: str | None = Field(None, examples=['standard'])
    expire_at: AwareDatetime | None = Field(None, examples=['2025-06-01T00:00:00Z'])
    metadata: dict[str, Any] | None = Field(
        None,
        examples=[{'vehicle_id': 'VH-042', 'route': 'SF-LA-101', 'weather': 'clear'}],
    )
    process_state: dict[str, str] | None = Field(
        None, examples=[{'validation': 'passed', 'indexing': 'pending'}]
    )
    tenant_id: str | None = Field(None, examples=['tenant-cyberorigin'])
    project_id: str | None = Field(None, examples=['project-autonomous-v1'])


class McapFinalizeUploadRequest(BaseModel):
    mcap_file_id: str = Field(..., examples=['mcap0012'])


class EvalResult(BaseModel):
    eval_result_id: str | None = None
    target_type: str | None = None
    target_id: str | None = None
    eval_name: str | None = None
    eval_version: str | None = None
    parameter_version: str | None = None
    run_id: str | None = None
    status: str | None = None
    result_payload: dict[str, Any] | None = None
    output_uri: str | None = None
    summary_uri: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class EvalResultRequest(BaseModel):
    target_type: str | None = None
    target_id: str | None = None
    eval_name: str
    eval_version: str
    parameter_version: str | None = None
    run_id: str | None = None
    status: str | None = None
    result_payload: dict[str, Any] | None = None
    output_uri: str | None = None
    summary_uri: str | None = None
    source_type: str | None = None
    source_name: str | None = None
    source_version: str | None = None


class EvalResultListResponse(BaseModel):
    items: list[EvalResult] | None = None
    total: int | None = None


class MetricEntry(BaseModel):
    metric_key: str | None = None
    metric_value: float | None = None
    metric_value_int: int | None = None
    metric_value_text: str | None = None
    metric_value_bool: bool | None = None
    metric_type: str | None = None
    eval_name: str | None = None
    eval_version: str | None = None
    run_id: str | None = None
    source_type: str | None = None
    recorded_at: AwareDatetime | None = None


class MetricListResponse(BaseModel):
    items: list[MetricEntry] | None = None


class Op(Enum):
    eq = 'eq'
    gt = 'gt'
    gte = 'gte'
    lt = 'lt'
    lte = 'lte'


class Metric(BaseModel):
    metric_key: str
    op: Op
    value: float | None = None


class Filters(BaseModel):
    lifecycle_state: str | None = None
    metrics: list[Metric] | None = None


class SearchByMetricsRequest(BaseModel):
    filters: Filters | None = None
    page: int | None = None
    page_size: int | None = None


class Item(BaseModel):
    key: str | None = None
    display_name: str | None = None
    metric_type: str | None = None
    metric_unit: str | None = None
    target_type: str | None = None
    higher_is_better: bool | None = None
    default_aggregation: str | None = None
    queryable: bool | None = None
    description: str | None = None


class MetricsRegistryResponse(BaseModel):
    items: list[Item] | None = None


class AlgoRegistryItem(BaseModel):
    key: str | None = None
    name: str | None = None
    version: str | None = None
    depends_on: list[str] | None = None


class TagRegistryItem(BaseModel):
    key: str | None = None
    description: str | None = None
    type: str | None = None
    values: list[str] | None = None
    max_length: int | None = None


class LifecycleState1(BaseModel):
    state: str | None = None


class SyncInfo(BaseModel):
    elasticsearch_ok: bool | None = None
    outbox_relay_enabled: bool | None = None
    outbox_es_subscriber_enabled: bool | None = None
    search_index_mode: str | None = None
    env: str | None = None
    admin_search_enabled: bool | None = None


class SyncProgress(BaseModel):
    postgres_assets_total: int | None = None
    elasticsearch_docs_total: int | None = None
    pg_es_gap: int | None = None
    pg_es_sync_ratio: float | None = None
    outbox_pending_events: int | None = None
    outbox_pending_claimable: int | None = None
    outbox_processing_events: int | None = None
    outbox_relay_safety_lag_sec: int | None = None
    oldest_pending_age_sec: int | None = None
    pg_max_event_seq: int | None = None
    outbox_published_max_seq: int | None = None
    seq_lag: int | None = None
    es_applied_min_seq: int | None = None
    consumer_lag: int | None = None
    checked_at: AwareDatetime | None = None


class SearchAggBucket(BaseModel):
    key: str | None = None
    doc_count: int | None = None


class Direction(Enum):
    upstream = 'upstream'
    downstream = 'downstream'
    both = 'both'


class LineageRelation(BaseModel):
    asset_id: str | None = None
    direction: Direction | None = None
    depth: int | None = None
    relation_types: list[str] | None = None


class Item1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    asset_id: str | None = None
    lineage_upstream_ids: list[str] | None = None
    lineage_downstream_ids: list[str] | None = None
    lineage_relation_types: list[str] | None = None
    lineage_relation: LineageRelation | None = None


class SearchAssetsResponse(BaseModel):
    items: list[Item1] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None
    aggregations: dict[str, list[SearchAggBucket]] | None = None


class LakehouseReport(BaseModel):
    total_assets: int | None = None
    total_deliveries: int | None = None
    total_customers: int | None = None
    total_mcap_files: int | None = None
    generated_at: AwareDatetime | None = None


class LakehouseStatus(BaseModel):
    healthy: bool | None = None
    enabled: bool | None = None
    backend: str | None = None
    project: str | None = None
    dataset: str | None = None


class LakehouseTableCount(BaseModel):
    table_name: str | None = None
    row_count: int | None = None


class LakehouseTableListResponse(BaseModel):
    items: list[LakehouseTableCount] | None = None


class LakehouseOverviewResponse(BaseModel):
    active_assets: int | None = None
    asset_total: int | None = None
    bronze_event_rows: int | None = None
    data_lag_hours: float | None = None
    day7_avg_new_assets: float | None = None
    mcap_total: int | None = None
    today_new_assets: int | None = None
    week_new_assets: int | None = None


class LakehouseEventDailyItem(BaseModel):
    event_date: date_aliased | None = None
    event_count: int | None = None


class LakehouseEventDailyResponse(BaseModel):
    items: list[LakehouseEventDailyItem] | None = None


class LakehouseAssetGrowthItem(BaseModel):
    date: date_aliased | None = None
    cumulative: int | None = None
    daily_delta: int | None = None


class LakehouseAssetGrowthResponse(BaseModel):
    items: list[LakehouseAssetGrowthItem] | None = None


class Item2(BaseModel):
    key: str | None = None
    count: int | None = None


class LakehouseItemsResponse(BaseModel):
    type_stats: Any | None = None
    items: list[Item2] | None = None


class FailureClusterItem(BaseModel):
    failure_mode: str | None = None
    algo_name: str | None = None
    affected_assets: int | None = None
    ratio: float | None = None


class BronzeSyncProgress(BaseModel):
    outbox_published_max_seq: int | None = None
    bronze_max_event_seq: int | None = None
    bronze_lag_events: int | None = None
    bronze_last_ingested_at: AwareDatetime | None = None
    bronze_stale_seconds: float | None = None
    checked_at: AwareDatetime | None = None


class SyncStatusData(BaseModel):
    dagster_run_id: str | None = None
    checked_at: AwareDatetime | None = None
    pg_total_count: int | None = None
    iceberg_total_count: int | None = None
    count_diff_pct: float | None = None
    pg_status_dist: Any | None = None
    iceberg_status_dist: Any | None = None
    status_diff: Any | None = None
    is_alert: bool | None = None
    iceberg_max_seq: int | None = None


class SyncStatusResponse(BaseModel):
    available: bool | None = None
    source: str | None = None
    message: str | None = None
    data: SyncStatusData | None = None


class AuditEventRow(BaseModel):
    event_id: str | None = None
    event_seq: int | None = None
    event_type: str | None = None
    aggregate_type: str | None = None
    asset_id: AssetID | None = None
    mcap_file_id: str | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    event_source: str | None = None
    actor_type: str | None = None
    actor_id: str | None = None
    run_id: str | None = None
    occurred_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class AuditSearchResponse(BaseModel):
    items: list[AuditEventRow] | None = None
    total: int | None = None
    next_cursor: str | None = None


class LineageNode(BaseModel):
    asset_id: AssetID | None = None
    parent_asset_id: str | None = None
    child_asset_id: str | None = None
    relation_type: str | None = None
    direction: str | None = None
    depth: int | None = None
    method: str | None = None
    algo_name: str | None = None
    algo_version: str | None = None
    run_id: str | None = None
    created_at: AwareDatetime | None = None


class LineageSearchResponse(BaseModel):
    nodes: list[LineageNode] | None = None


class LineageResponse(BaseModel):
    asset_id: AssetID | None = None
    upstream: Any | None = None
    downstream: Any | None = None


class ProvenanceEntry(BaseModel):
    source_asset_id: AssetID | None = None
    relation_type: str | None = None
    method: str | None = None
    algo_name: str | None = None
    run_id: str | None = None
    created_at: AwareDatetime | None = None


class AssetProvenanceResponse(BaseModel):
    asset_id: AssetID | None = None
    root_asset_id: AssetID | None = None
    provenance: list[ProvenanceEntry] | None = None


class SearchReindexRequest(BaseModel):
    dry_run: bool | None = None
    page_size: int | None = None


class SearchReindexResponse(BaseModel):
    dry_run: bool | None = None
    total_assets: int | None = None
    indexed: int | None = None
    deleted: int | None = None
    failed: int | None = None
    duration_ms: int | None = None
    errors: list[str] | None = None
    elasticsearch_doc_count: int | None = None
    assets_scanned: int | None = None
    documents_indexed: int | None = None
    documents_deleted: int | None = None


class SearchReindexJobView(BaseModel):
    id: str | None = None
    job_type: str | None = None
    status: str | None = None
    progress_n: int | None = None
    progress_of: int | None = None
    error_detail: str | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class SearchReindexJobsListResponse(BaseModel):
    items: list[SearchReindexJobView] | None = None


class SearchOutboxStatsResponse(BaseModel):
    publish_state_counts: dict[str, int] | None = None
    outbox_dlq_rows: int | None = None


class SearchAuditResponse(BaseModel):
    pg_assets: int | None = None
    elasticsearch_docs: int | None = None
    missing_in_elasticsearch: int | None = None
    orphan_in_elasticsearch: int | None = None
    consistency: float | None = None
    target: float | None = None
    sample_missing_ids: list[str] | None = None
    sample_orphan_ids: list[str] | None = None
    duration_ms: int | None = None


class BatchDeleteRequest(BaseModel):
    asset_ids: list[AssetID] | None = None
    import_batch: str | None = None
    include_mcap_files: bool | None = None
    dry_run: bool | None = None
    chunk_size: int | None = None


class BatchDeleteResponse(BaseModel):
    deleted_count: int | None = None
    dry_run: bool | None = None


class Segment(BaseModel):
    start_ns: int | None = None
    end_ns: int | None = None
    asset_type: str | None = None
    metadata: dict[str, Any] | None = None


class InternalCommitSegmentsRequest(BaseModel):
    mcap_file_id: McapFileID | None = None
    segments: list[Segment] | None = None


class LoginRequest(BaseModel):
    token: str = Field(..., examples=['g-databrew-admin-token-xxx'])


class EmailLoginRequest(BaseModel):
    email: EmailStr = Field(..., examples=['user@example.com'])


class LoginResponse(BaseModel):
    authenticated: bool | None = Field(None, examples=[True])
    email: EmailStr | None = Field(None, examples=['user@example.com'])
    role: str | None = Field(None, examples=['admin'])


class ChildAssetCreateRequest(BaseModel):
    start_timestamp_ns: conint(ge=1) = Field(
        ...,
        description='Start timestamp in nanoseconds',
        examples=[1700000000000000000],
    )
    end_timestamp_ns: conint(ge=1) = Field(
        ..., description='End timestamp in nanoseconds', examples=[1700000100000000000]
    )
    split_method: str | None = Field(
        None,
        description='Split method. When unset or manual/rule:* → edge is split_from; algo:* → edge is derived_from',
        examples=['manual'],
    )
    split_run_id: str | None = Field(None, examples=['run-abc123'])
    metadata: dict[str, Any] | None = Field(
        None,
        description='Optional metadata for the new child asset',
        examples=[{'source': 'manual-annotation'}],
    )


class CreateAssetRequest(BaseModel):
    asset_id: AssetID | None = Field(
        None, description='Optional — server generates if omitted'
    )
    logical_asset_id: str | None = Field(
        None, description='Logical asset group ID', examples=['aaaaaaaa']
    )
    mcap_file_id: McapFileID | None = Field(None, description='Source MCAP file')
    start_timestamp_ns: conint(ge=1) = Field(
        ...,
        description='Start timestamp in nanoseconds',
        examples=[1700000000000000000],
    )
    end_timestamp_ns: conint(ge=1) = Field(
        ..., description='End timestamp in nanoseconds', examples=[1700000360000000000]
    )
    reviewer: str = Field(
        ..., description='Reviewer name for the asset', examples=['zhangsan']
    )
    owner: str | None = Field(None, description='Owner name', examples=['lisi'])
    type: str | None = Field(
        None, description='Segment type (legacy)', examples=['segment']
    )
    asset_type: str | None = Field(
        None,
        description='Asset type (e.g. segment, clip, frame_set, derived_asset)',
        examples=['segment'],
    )
    status: str | None = Field(
        None, description='Legacy lifecycle status', examples=['ready']
    )
    lifecycle_state: str | None = Field(
        None, description='Lifecycle state', examples=['ready']
    )
    env: str | None = Field(None, examples=['production'])
    task: str | None = Field(None, examples=['data-ingestion-pipeline-v3'])
    tags: dict[str, str] | None = Field(
        None,
        description='Key→value tags',
        examples=[{'project': 'alpha', 'batch': '2024-03'}],
    )
    files: dict[str, str] | None = Field(
        None,
        description='Key→value file URIs',
        examples=[{'image': 'gs://bucket/preview.png', 'raw': 'gs://bucket/data.bin'}],
    )
    metadata: dict[str, Any] | None = Field(
        None, examples=[{'source': 'lidar-sensor-01', 'resolution': '1920x1080'}]
    )
    lifecycle_meta: dict[str, Any] | None = Field(
        None, examples=[{'reason': 'quality-review-passed'}]
    )
    retention_tier: str | None = Field(None, examples=['standard'])
    expire_at: AwareDatetime | None = Field(None, examples=['2025-06-01T00:00:00Z'])
    storage_uri: str | None = Field(
        None, examples=['gs://databrew-assets/segments/a1b2c3d4.mcap']
    )
    thumb_uri: str | None = Field(
        None, examples=['gs://databrew-thumbnails/a1b2c3d4.jpg']
    )
    asset_level: int | None = Field(None, examples=[1])
    parent_asset_id: AssetID | None = None
    root_asset_id: AssetID | None = None
    segment_index: int | None = Field(None, examples=[3])
    parent_start_offset_ms: int | None = Field(None, examples=[120000])
    parent_end_offset_ms: int | None = Field(None, examples=[240000])
    split_method: str | None = Field(None, examples=['manual'])
    split_algo_name: str | None = Field(None, examples=['scene-detector'])
    split_algo_version: str | None = Field(None, examples=['2.1.0'])
    split_run_id: str | None = Field(None, examples=['run-abc123'])
    split_reason: str | None = Field(None, examples=['scene-change-at-12s'])
    delivery_count: int | None = Field(None, examples=[2])
    last_delivered_at: AwareDatetime | None = Field(
        None, examples=['2025-05-01T10:30:00Z']
    )
    last_delivered_to: str | None = Field(None, examples=['customer-alpha'])


class BatchGetAssetsRequest(BaseModel):
    asset_ids: list[AssetID] = Field(
        ...,
        description='List of asset IDs to fetch (max 100)',
        examples=[['a1b2c3d4', 'e5f6g7h8']],
        max_length=100,
    )


class PromoteRevisionRequest(BaseModel):
    logical_asset_id: str | None = Field(
        None, description='Logical asset group to promote into', examples=['aaaaaaaa']
    )
    revision_of: str | None = Field(
        None, description='Source revision identifier', examples=['a1b2c3d4']
    )
    owner: str | None = Field(
        None, description='Owner of the new revision', examples=['lisi']
    )


class PipelineArgument(BaseModel):
    name: str | None = None
    value: str | None = None
    from_: str | None = Field(None, alias='from')


class PipelinePort(BaseModel):
    name: str
    type: str
    desc: str | None = None
    default_value: str | None = None


class PipelineNodeComponentResources(BaseModel):
    cpu: str | None = Field(None, examples=['500m'])
    memory: str | None = Field(None, examples=['512Mi'])
    disk: str | None = Field(None, examples=['1Gi'])
    gpu: str | None = Field(None, examples=['1'])
    computeTier: str | None = None
    env: dict[str, str] | None = None


class Type(Enum):
    container = 'container'
    script = 'script'
    resource = 'resource'
    suspend = 'suspend'


class PipelineNodeComponent(BaseModel):
    name: str
    image: str
    type: Type | None = None
    source: str | None = None
    command: list[str] | None = None
    args: list[PipelineArgument] | None = None
    resources: PipelineNodeComponentResources | None = None
    componentId: str | None = None
    releaseId: str | None = None
    componentVersionLabel: str | None = None


class Mode1(Enum):
    saved = 'saved'


class PipelineNodeRuntimeConfig(BaseModel):
    mode: Mode1
    configId: str
    version: conint(ge=1)
    fileName: str | None = None
    mountPath: str = Field(..., examples=['/workspace/configs'])
    targetFilename: str = Field(..., examples=['detector.yaml'])
    displayName: str | None = None


class PipelineNodeRuntimeSecretMount(BaseModel):
    resourceId: str = Field(..., description='Runtime secret catalog ID')
    mountPath: str | None = Field(
        None,
        description='Absolute path mounted inside the node container. Defaults to the catalog path.',
        examples=['/mnt/secrets'],
    )
    displayName: str | None = None


class PipelineNodeRuntimeStorageMount(BaseModel):
    resourceId: str = Field(..., description='Runtime storage catalog ID')
    mountPath: str | None = Field(
        None,
        description='Absolute path mounted inside the node container. Defaults to the catalog path.',
        examples=['/workspace/models'],
    )
    readOnly: bool | None = Field(
        None,
        description='Overrides catalog read mode when the resource supports write access.',
    )
    displayName: str | None = None


class Kind(Enum):
    secretProviderClass = 'secretProviderClass'  # pragma: allowlist secret


class RuntimeSecretMountResource(BaseModel):
    id: str
    name: str
    description: str | None = None
    kind: Kind
    secretProviderClass: str = Field(
        ..., description='Kubernetes SecretProviderClass name'
    )
    defaultMountPath: str = Field(..., examples=['/mnt/secrets'])
    readOnly: bool = Field(..., examples=[True])
    targetIds: list[str] | None = None


class Kind1(Enum):
    pvc = 'pvc'
    emptyDir = 'emptyDir'


class RuntimeStorageMountResource(BaseModel):
    id: str
    name: str
    description: str | None = None
    kind: Kind1
    pvcName: str | None = Field(None, description='Kubernetes PVC name when kind=pvc')
    defaultMountPath: str = Field(..., examples=['/workspace/scratch'])
    readOnly: bool
    allowWrite: bool
    targetIds: list[str] | None = None


class RuntimeMountCatalog(BaseModel):
    secrets: list[RuntimeSecretMountResource]
    storage: list[RuntimeStorageMountResource]


class PipelineNodeDefinition(BaseModel):
    id: str
    component: PipelineNodeComponent
    inputs: list[PipelinePort] | None = None
    outputs: list[PipelinePort] | None = None
    runtimeConfig: PipelineNodeRuntimeConfig | None = None
    runtimeSecrets: list[PipelineNodeRuntimeSecretMount] | None = None
    storageMounts: list[PipelineNodeRuntimeStorageMount] | None = None


class PipelineEdgeDefinition(BaseModel):
    source: str = Field(..., examples=['step-a.output'])
    target: str = Field(..., examples=['step-b.input'])


class AssetSelection(BaseModel):
    assetIds: list[str] | None = None
    assetQuery: str | None = None


class PipelineDefinition(BaseModel):
    name: str
    version: str | None = None
    nodes: list[PipelineNodeDefinition]
    edges: list[PipelineEdgeDefinition]
    assetSelection: AssetSelection | None = None


class PipelineTemplate(BaseModel):
    id: str | None = Field(None, description='Template ID')
    name: str | None = Field(None, description='Template name')
    version: int | None = Field(None, description='Template version number')
    versionCount: int | None = Field(
        None, description='Number of saved versions for the same template name'
    )
    pipeline: PipelineDefinition | None = None
    nodeCount: int | None = Field(None, description='Number of nodes in the pipeline')
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class Status3(Enum):
    available = 'available'
    unavailable = 'unavailable'


class ExecutionTarget(BaseModel):
    id: str | None = Field(None, description='Stable execution target ID')
    name: str | None = Field(None, description='Human-readable target name')
    cluster: str | None = Field(None, description='Cluster label or identifier')
    namespace: str | None = Field(
        None, description='Kubernetes namespace for Argo workflows'
    )
    serviceAccount: str | None = Field(
        None, description='Kubernetes service account for workflow pods'
    )
    argoServerUrl: str | None = Field(
        None,
        description='Argo Server URL when persisted. May be omitted/redacted by API responses.',
    )
    argoAuthSecretRef: str | None = Field(
        None, description='Secret reference for Argo auth'
    )
    argoInsecureSkipTls: bool | None = None
    argoCaCertRef: str | None = None
    argoServerConfigured: bool | None = Field(
        None, description='Whether backend Argo client is configured'
    )
    status: Status3 | None = None
    enabled: bool | None = None
    isDefault: bool | None = None
    description: str | None = None
    resourceDefaults: dict[str, Any] | None = None
    quotaPolicy: dict[str, Any] | None = None
    labels: dict[str, Any] | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class PipelineRunNode(BaseModel):
    id: str | None = None
    runId: str | None = None
    pipelineNodeId: str | None = None
    argoNodeId: str | None = None
    argoNodeName: str | None = None
    displayName: str | None = None
    templateName: str | None = None
    type: str | None = None
    phase: str | None = None
    message: str | None = None
    podName: str | None = None
    hostNodeName: str | None = None
    children: list[str] | None = None
    inputs: dict[str, Any] | None = None
    outputs: dict[str, Any] | None = None
    resourcesDuration: dict[str, Any] | None = None
    resourceSummary: dict[str, Any] | None = None
    logRef: str | None = Field(
        None, description='Relative logs endpoint for this pod when available'
    )
    estimatedCostUsd: float | None = Field(
        None, description='Best-effort estimated node cost in USD.'
    )
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class PipelineRun(BaseModel):
    id: str | None = Field(None, description='Pipeline run ID')
    templateId: str | None = None
    pipelineName: str | None = None
    templateVersion: int | None = None
    workflowName: str | None = None
    executionTargetId: str | None = None
    targetSnapshot: dict[str, Any] | None = None
    status: str | None = None
    nodeCount: int | None = None
    assetIds: list[str] | None = None
    assetCount: int | None = None
    noAssetRun: bool | None = None
    manifest: str | None = None
    pipelineJSON: dict[str, Any] | None = None
    argoNamespace: str | None = None
    argoWorkflowUid: str | None = None
    message: str | None = None
    failureReason: str | None = Field(
        None,
        description='Normalized terminal failure reason derived from Run ledger, events, or runtime diagnostics.',
        examples=['unschedulable'],
    )
    blockingReason: str | None = Field(
        None,
        description='Normalized active-state blocking reason when the Run is waiting or blocked.',
        examples=['runtime_not_submitted'],
    )
    blockingMessage: str | None = Field(
        None,
        description='Human-readable blocking diagnostic for active Runs.',
        examples=['Run 已创建，正在等待提交到运行时。'],
    )
    executionTarget: ExecutionTarget | None = None
    nodes: list[PipelineRunNode] | None = None
    totalEstimatedCost: float | None = Field(
        None,
        description='Sum of node estimated costs in USD when pricing data is available.',
    )
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None


class Mode2(Enum):
    saved = 'saved'
    upload = 'upload'
    inline = 'inline'


class DeployConfigSelection(BaseModel):
    mode: Mode2 = Field(
        ...,
        description='saved = select a platform-stored config; upload = ad hoc local file; inline = deploy-time editor content.',
    )
    configId: str | None = Field(None, description='Required when mode=saved.')
    version: int | None = Field(
        None,
        description='Optional saved config version. Defaults to the latest active version when omitted.',
    )
    fileName: str | None = Field(
        None,
        description='Source file name used in the deploy UI and ConfigMap projection.',
    )
    content: str | None = Field(
        None,
        description='Required when mode=upload or mode=inline. Raw file content projected into a request-scoped ConfigMap.',
    )
    mountPath: str = Field(
        ...,
        description='Directory mounted into each pipeline step container.',
        examples=['/workspace/configs'],
    )
    targetFilename: str = Field(
        ...,
        description='Final file name inside mountPath.',
        examples=['app-config.yaml'],
    )


class SubjectType(Enum):
    run = 'run'
    workflow = 'workflow'
    node = 'node'
    pod = 'pod'


class PipelineRunEvent(BaseModel):
    id: str | None = Field(None, description='Event ID')
    runId: str | None = Field(None, description='Pipeline run ID')
    workflowName: str | None = Field(None, description='Argo workflow name when known')
    eventType: str | None = Field(
        None,
        description='Machine-readable event type such as run_submitted or node_failed.',
    )
    subjectType: SubjectType | None = None
    subjectId: str | None = None
    status: str | None = None
    message: str | None = None
    reason: str | None = None
    payload: dict[str, Any] | None = None
    idempotencyKey: str | None = Field(
        None,
        description='Deterministic key used by the backend to deduplicate watcher observations.',
    )
    sequence: int | None = Field(
        None,
        description='Monotonic run event sequence used for chronological pagination.',
    )
    occurredAt: AwareDatetime | None = None
    observedAt: AwareDatetime | None = None
    createdAt: AwareDatetime | None = None


class PipelineRunEventList(BaseModel):
    items: list[PipelineRunEvent] | None = None
    nextCursor: int | None = None
    total: int | None = Field(
        None, description='Number of events returned in this page.'
    )


class PipelineRunWatcherState(BaseModel):
    id: str | None = None
    lastSyncedAt: AwareDatetime | None = None
    lastScanStartedAt: AwareDatetime | None = None
    lastScanFinishedAt: AwareDatetime | None = None
    lastSuccessAt: AwareDatetime | None = None
    lastErrorAt: AwareDatetime | None = None
    activeScanLimit: int | None = None
    lastSyncedRunCount: int | None = None
    consecutiveFailures: int | None = None
    totalScans: int | None = None
    totalErrors: int | None = None
    scanLagSeconds: int | None = None
    lastError: str | None = None
    healthy: bool | None = None
    stale: bool | None = None
    updatedAt: AwareDatetime | None = None


class CostSource(Enum):
    estimated_resource_duration = 'estimated_resource_duration'
    not_available = 'not_available'


class PipelineRunAssetNode(BaseModel):
    id: str | None = None
    runId: str | None = None
    assetId: str | None = None
    pipelineNodeId: str | None = None
    argoNodeId: str | None = None
    displayName: str | None = None
    status: str | None = None
    message: str | None = None
    podName: str | None = None
    logRef: str | None = None
    estimatedCostUsd: float | None = None
    costSource: CostSource | None = None
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class Summary(BaseModel):
    assetCount: int | None = None
    nodeCount: int | None = None
    statuses: dict[str, int] | None = None
    totalEstimatedCostUsd: float | None = None
    costSource: CostSource | None = None


class PipelineRunAssetNodeList(BaseModel):
    items: list[PipelineRunAssetNode] | None = None
    nextCursor: str | None = None
    total: int | None = None
    summary: Summary | None = None


class NodeSummary(BaseModel):
    nodeId: str | None = None
    displayName: str | None = None
    status: str | None = None
    podCount: int | None = None
    estimatedCostUsd: float | None = None
    costSource: str | None = None
    durationSeconds: int | None = None


class AssetNodeSummary(BaseModel):
    assetId: str | None = None
    nodeId: str | None = None
    displayName: str | None = None
    status: str | None = None
    estimatedCostUsd: float | None = None
    costSource: str | None = None


class PipelineRunCostSummary(BaseModel):
    runId: str | None = None
    totalEstimatedCostUsd: float | None = None
    costSource: CostSource | None = None
    nodeSummaries: list[NodeSummary] | None = None
    assetNodeSummaries: list[AssetNodeSummary] | None = None
    generatedAt: AwareDatetime | None = None


class RunInput(BaseModel):
    id: str | None = None
    runId: str | None = None
    nodeId: str | None = None
    type: str | None = Field(
        None,
        description='Input kind, for example asset, runtime_target, config, or parameter.',
    )
    refId: str | None = None
    refVersion: str | None = None
    fileName: str | None = None
    mountPath: str | None = None
    targetFilename: str | None = None
    contentHash: str | None = Field(
        None,
        description='Immutable hash of config content when available. Raw config content is not returned.',
    )
    projectionKey: str | None = Field(
        None,
        description='Runtime materialization key for config projection when available.',
    )
    source: str | None = None
    snapshot: dict[str, Any] | None = None


class RunInputList(BaseModel):
    runId: str | None = None
    items: list[RunInput] | None = None
    total: int | None = None


class RunOutput(BaseModel):
    id: str | None = None
    runId: str | None = None
    nodeId: str | None = None
    type: str | None = Field(
        None, description='Output kind, for example node_outputs, logs, or metrics.'
    )
    refId: str | None = None
    uri: str | None = None
    snapshot: dict[str, Any] | None = None


class RunOutputList(BaseModel):
    runId: str | None = None
    items: list[RunOutput] | None = None
    total: int | None = None


class RunRelation(BaseModel):
    id: str | None = None
    parentRunId: str | None = None
    childRunId: str | None = None
    relationType: str | None = Field(
        None,
        description='Relationship kind, for example batch_child, retry_of, resubmit_of, or rerun_of.',
    )
    source: str | None = Field(
        None,
        description='Relation source, for example run_kernel, run_relations, pipeline_runs.batch_job_id, or pipeline_run_events.',
    )
    assetId: str | None = None
    snapshot: dict[str, Any] | None = None


class RunBlockingReason(BaseModel):
    reason: str | None = Field(
        None,
        description='Normalized reason code such as unschedulable, resource_incompatible, image_startup, runtime_not_submitted, runtime_missing, or run_failed.',
    )
    message: str | None = Field(
        None, description='Representative diagnostic message for this reason.'
    )
    count: int | None = Field(
        None,
        description='Number of child Runs matching this reason when returned in a summary.',
    )
    exampleRunId: str | None = Field(
        None, description='Example Run ID carrying this reason.'
    )
    exampleAssetId: str | None = Field(
        None, description='Example asset ID carrying this reason when available.'
    )
    source: str | None = Field(
        None, description='Projection source for the diagnostic.'
    )


class Runtime(BaseModel):
    runtimeType: str | None = Field(None, examples=['argo'])
    workflowName: str | None = None
    namespace: str | None = None
    uid: str | None = None
    status: str | None = None
    message: str | None = None
    executionTargetId: str | None = None
    targetSnapshot: dict[str, Any] | None = None
    debugUrl: str | None = None


class RunRuntime(BaseModel):
    runId: str | None = None
    runtime: Runtime | None = None


class RunNodeList(BaseModel):
    items: list[PipelineRunNode] | None = None
    total: int | None = None


class RunOperationResponse(BaseModel):
    message: str | None = None


class PipelineComponentResources(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    cpu: str | None = Field(
        None,
        description='Kubernetes CPU quantity, for example "500m" or "4".',
        examples=['4000m'],
    )
    memory: str | None = Field(
        None, description='Kubernetes memory quantity.', examples=['16Gi']
    )
    disk: str | None = Field(
        None, description='Kubernetes ephemeral storage quantity.', examples=['50Gi']
    )
    gpu: str | None = Field(
        None,
        description='Kubernetes nvidia.com/gpu quantity emitted as a GPU limit.',
        examples=['1'],
    )
    computeTier: str | None = Field(
        None,
        description='DataBrew compute tier metadata for future scheduling, quota, and cost policy.',
        examples=['gpu-l4'],
    )
    type: str | None = Field(None, description='Component runtime type mirror.')
    command: list[str] | None = None
    args: list[str] | None = None
    env: dict[str, str] | None = None


class FileType(Enum):
    yaml = 'yaml'
    json = 'json'


class Lifecycle(Enum):
    draft = 'draft'
    ready = 'ready'
    deprecated = 'deprecated'


class Status4(Enum):
    draft = 'draft'
    ready = 'ready'
    deprecated = 'deprecated'


class PipelineConfigVersion(BaseModel):
    id: str | None = None
    configId: str | None = None
    version: conint(ge=1) | None = None
    status: Status4 | None = None
    content: constr(max_length=1048576) | None = Field(
        None, description='Present only on single-version detail responses.'
    )
    contentSha256: str | None = None
    contentSizeBytes: conint(ge=0, le=1048576) | None = None
    summary: str | None = None
    author: str | None = None
    createdAt: AwareDatetime | None = None


class PipelineConfigCreateRequest(BaseModel):
    name: str
    description: str | None = None
    tags: list[str] | None = None
    fileType: FileType | None = Field(
        None, description='Optional; inferred from the file name when omitted.'
    )
    lifecycle: Lifecycle | None = 'draft'
    scope: str | None = 'dev'
    content: constr(max_length=1048576)
    summary: str | None = None


class PipelineConfigUpdateRequest(BaseModel):
    name: str
    description: str | None = None
    tags: list[str] | None = None
    fileType: FileType | None = None
    lifecycle: Lifecycle | None = None


class PipelineConfigVersionCreateRequest(BaseModel):
    status: Status4 | None = 'draft'
    content: constr(max_length=1048576)
    summary: str | None = None


class Channel(Enum):
    dev = 'dev'
    preview = 'preview'
    candidate = 'candidate'
    rc = 'rc'
    prod = 'prod'


class SourceRefType(Enum):
    tag = 'tag'
    commit = 'commit'
    branch = 'branch'
    pr = 'pr'


class Status6(Enum):
    ready = 'ready'
    failed = 'failed'
    pending = 'pending'
    deprecated = 'deprecated'


class ValidationStatus(Enum):
    passed = 'passed'
    failed = 'failed'


class RefType(Enum):
    tag = 'tag'
    commit = 'commit'
    branch = 'branch'
    pr = 'pr'


class ComponentReleaseIngestSource(BaseModel):
    provider: str | None = Field(None, examples=['cloud-build'])
    repo: str | None = Field(
        None, examples=['CyberOrigin2077/automated-processing-gcloud']
    )
    ref: str | None = Field(None, examples=['refs/heads/main'])
    refType: RefType | None = Field(None, examples=['branch'])
    commit: str | None = Field(None, examples=['abc123'])
    buildId: str | None = Field(None, examples=['1e86eab9-9250-41c5-b905-8ff3c6de23af'])
    trigger: str | None = Field(None, examples=['hand-track-stereo-build-trigger'])


class PortDef(BaseModel):
    name: str | None = None
    type: str | None = None
    desc: str | None = None
    default_value: str | None = None


class EnvVarDef(BaseModel):
    name: str | None = None
    value: str | None = None


class WorkflowSummary(BaseModel):
    name: str | None = None
    status: str | None = None
    nodeCount: int | None = None
    createdAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None


class Kind2(Enum):
    runtime = 'runtime'
    dag = 'dag'
    fallback = 'fallback'


class WorkflowDagEdge(BaseModel):
    id: str | None = Field(None, description='Stable edge identifier for DAG rendering')
    source: str | None = Field(None, description='Source workflow node id')
    target: str | None = Field(None, description='Target workflow node id')
    kind: Kind2 | None = Field(
        None,
        description='Edge origin. `dag` preserves logical dependencies such as failed upstream to omitted downstream steps.',
    )


class WorkflowNodeDebugCapabilities(BaseModel):
    execEnabled: bool | None = Field(
        None,
        description='Whether Pod terminal exec is enabled for this node and target.',
    )
    logStreamEnabled: bool | None = None
    metricsEnabled: bool | None = None
    costEnabled: bool | None = None
    reason: str | None = Field(
        None, description='Human-readable terminal availability reason.'
    )
    allowedCommands: list[str] | None = None
    maxSessionSeconds: int | None = None


class CreatePodTerminalSessionRequest(BaseModel):
    containerName: str | None = Field(
        None,
        description="Optional container name. Defaults to the workflow node's main container when omitted.",
    )
    command: str | None = Field(
        'sh', description='Allowed command preset such as `sh`, `pwd`, `ls`, or `env`.'
    )


class Status8(Enum):
    created = 'created'
    attached = 'attached'
    terminated = 'terminated'
    failed = 'failed'
    timed_out = 'timed_out'


class PodTerminalSession(BaseModel):
    id: str
    runId: str | None = None
    workflowName: str
    nodeId: str
    podName: str
    containerName: str | None = None
    executionTargetId: str | None = None
    cluster: str | None = None
    namespace: str
    command: str
    status: Status8
    attachUrl: str | None = Field(
        None,
        description='One-time backend attach URL. Does not expose Kubernetes credentials.',
    )
    expiresAt: AwareDatetime
    createdAt: AwareDatetime
    attachedAt: AwareDatetime | None = None
    endedAt: AwareDatetime | None = None
    errorCode: str | None = None
    errorMessage: str | None = None


class WorkflowNodePodContainer(BaseModel):
    name: str
    image: str | None = None
    ready: bool
    restartCount: int
    state: str | None = Field(None, description='Running')


class WorkflowNodePodCondition(BaseModel):
    type: str
    status: str
    reason: str | None = None
    message: str | None = None
    lastTransitionTime: AwareDatetime | None = None


class WorkflowNodePodEvent(BaseModel):
    type: str
    reason: str
    message: str
    count: int | None = None
    firstTimestamp: AwareDatetime | None = None
    lastTimestamp: AwareDatetime | None = None


class WorkflowOperationResponse(BaseModel):
    message: str | None = Field(None, examples=['ok'])
    workflowName: str | None = Field(
        None,
        description='Newly created workflow name when the operation creates one, such as resubmit.',
    )
    pipelineRunId: str | None = Field(
        None,
        description='DataBrew pipeline run id created for the new workflow when available.',
    )


class BackfillJob(BaseModel):
    id: str | None = None
    name: str | None = None
    templateId: str | None = None
    templateVersion: int | None = None
    filterJson: dict[str, Any] | None = None
    totalCount: int | None = None
    completedCount: int | None = None
    failedCount: int | None = None
    pilotCount: int | None = None
    pilotPhase: str | None = Field(None, description='none | running | review | done')
    status: str | None = Field(
        None, description='running | paused | completed | failed'
    )
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class BackfillItem(BaseModel):
    id: str | None = None
    jobId: str | None = None
    assetId: str | None = None
    status: str | None = Field(
        None, description='pending | running | completed | failed | cancelled'
    )
    workflowName: str | None = None
    errorMessage: str | None = None
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    createdAt: AwareDatetime | None = None


class Subtasks(BaseModel):
    total: int | None = None
    completed: int | None = None
    failed: int | None = None
    running: int | None = None
    pending: int | None = None
    paused: bool | None = None


class Node(BaseModel):
    pipelineNodeId: str | None = None
    displayName: str | None = None
    dagOrder: int | None = None
    counts: dict[str, int] | None = None
    attempted: int | None = None
    failureRate: float | None = None


class DataCoverage(BaseModel):
    runsWithNodeRows: int | None = None
    runsTotal: int | None = None
    complete: bool | None = None


class BatchNodeSummary(BaseModel):
    batchJobId: str | None = None
    templateId: str | None = None
    templateVersion: int | None = None
    subtasks: Subtasks | None = None
    nodes: list[Node] | None = None
    dataCoverage: DataCoverage | None = None
    generatedAt: AwareDatetime | None = None


class Item3(BaseModel):
    backfillItemId: str | None = None
    assetId: str | None = None
    runId: str | None = None
    workflowName: str | None = None
    pipelineNodeId: str | None = None
    displayName: str | None = None
    status: str | None = None
    message: str | None = None
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None


class BatchNodeFailureList(BaseModel):
    items: list[Item3] | None = None
    total: int | None = None
    page: int | None = None
    pageSize: int | None = None


class Scope1(Enum):
    failed = 'failed'
    pending = 'pending'
    incomplete = 'incomplete'
    completed = 'completed'
    custom = 'custom'
    node_failed = 'node_failed'


class BackfillRerunRequest(BaseModel):
    scope: Scope1 | None = None
    templateId: str | None = None
    templateVersion: int | None = None
    itemIds: list[str] | None = None
    assetIds: list[str] | None = None
    pipelineNodeId: str | None = None
    dryRun: bool | None = None


class Status9(Enum):
    accepted = 'accepted'
    partial_success = 'partial_success'
    succeeded = 'succeeded'
    failed = 'failed'
    noop = 'noop'


class SkippedItem(BaseModel):
    itemId: str | None = None
    reason: str | None = None


class BackfillRerunResult(BaseModel):
    status: Status9 | None = None
    dryRun: bool | None = None
    matchedCount: int | None = None
    retriedCount: int | None = None
    templateId: str | None = None
    templateVersion: int | None = None
    skipped: list[SkippedItem] | None = None


class Asset(BaseModel):
    asset_id: AssetID | None = None
    mcap_file_id: McapFileID | None = None
    segment_locator: str | None = Field(
        None, description='Deterministic SHA-1 of mcap_file_id + start_ns + end_ns'
    )
    start_timestamp_ns: int | None = None
    end_timestamp_ns: int | None = None
    duration_sec: float | None = Field(
        None, description='Legacy: duration in seconds (backward compat)'
    )
    duration_ms: int | None = None
    lifecycle_state: LifecycleState | None = None
    asset_type: str | None = Field(
        None, description='Asset type (e.g. segment, clip, frame_set, derived_asset).'
    )
    status: str | None = Field(
        None,
        description='Legacy derived status (API-only, not stored). One of: approved, rejected, archived, superseded.',
    )
    owner: str | None = None
    reviewer: str | None = None
    type: str | None = Field(None, description='Legacy: mirrors asset_type.')
    retention_tier: str | None = None
    expire_at: AwareDatetime | None = None
    storage_uri: str | None = None
    thumb_uri: str | None = None
    asset_level: int | None = None
    parent_asset_id: AssetID | None = None
    root_asset_id: AssetID | None = None
    split_method: str | None = None
    split_algo_name: str | None = None
    split_algo_version: str | None = None
    split_run_id: str | None = None
    split_reason: str | None = None
    segment_index: int | None = None
    parent_start_offset_ms: int | None = None
    parent_end_offset_ms: int | None = None
    delivery_count: int | None = None
    last_delivered_at: AwareDatetime | None = None
    last_delivered_to: str | None = None
    env: str | None = None
    task: str | None = None
    version: int | None = None
    algo_results: dict[str, str] | None = None
    tags: dict[str, str] | None = Field(
        None,
        description='Flat key→value map (last-write-wins). For multi-source use tags_detailed.',
    )
    tags_detailed: list[AssetTag] | None = None
    files: dict[str, str] | None = None
    files_json: dict[str, Any] | None = Field(
        None, description='JSONB alternative to files.'
    )
    algo_inputs_uris: dict[str, str] | None = None
    annot_inputs_uris: dict[str, str] | None = None
    metadata: dict[str, Any] | None = None
    lifecycle_meta: dict[str, Any] | None = None
    logical_asset_id: str | None = None
    revision: int | None = None
    is_current: bool | None = None
    tenant_id: str | None = None
    project_id: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class AssetListResponse(BaseModel):
    items: list[Asset] | None = None
    total: int | None = None
    page: int | None = None
    page_size: int | None = None


class DeliveryCommitC2Response(BaseModel):
    delivery_id: str | None = None
    status: str | None = None
    violations: list[DeliveryRuleViolation] | None = None


class PipelineDeployment(BaseModel):
    id: str | None = Field(None, description='Deployment ID')
    templateId: str | None = Field(None, description='Optional linked template ID')
    templateVersion: int | None = Field(
        None, description='Version of the linked template snapshot'
    )
    pipelineName: str | None = Field(
        None, description='Pipeline name from the deployed pipeline'
    )
    workflowName: str | None = Field(None, description='Resulting Argo workflow name')
    status: str | None = Field(
        None, description='Deployment/workflow status (Succeeded'
    )
    nodeCount: int | None = None
    assetIds: list[str] | None = Field(
        None, description='Asset IDs selected for this run, when any'
    )
    assetCount: int | None = Field(None, description='Number of selected assets')
    executionTarget: ExecutionTarget | None = None
    manifest: str | None = None
    pipelineJSON: dict[str, Any] | None = Field(
        None, description='Snapshot of the pipeline definition at deployment time'
    )
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None


class RunChildSummary(BaseModel):
    total: int | None = None
    statuses: dict[str, int] | None = None
    aggregateStatus: str | None = Field(
        None, description='Deterministic aggregate child status.'
    )
    activeCount: int | None = None
    terminalCount: int | None = None
    succeededCount: int | None = None
    failedCount: int | None = None
    cancelledCount: int | None = None
    pendingCount: int | None = None
    runningCount: int | None = None
    suspendedCount: int | None = None
    hasFailures: bool | None = Field(
        None,
        description='True when any child Run has failed, errored, expired, or been cancelled.',
    )
    hasBlocking: bool | None = Field(
        None,
        description='True when any child Run is pending/suspended or has a blocking diagnostic reason.',
    )
    healthStatus: str | None = Field(
        None,
        description='Aggregate health hint such as healthy, warning, degraded, failed, or pending.',
    )
    topFailureReasons: list[RunBlockingReason] | None = Field(
        None,
        description='Top normalized failure or blocking reasons across immediate child Runs.',
    )


class PipelineComponent(BaseModel):
    id: str | None = Field(None, description='Component ID')
    name: str | None = None
    type: Type | None = None
    description: str | None = None
    image: str | None = Field(None, description='Docker image name')
    tag: str | None = Field(None, description='Docker image tag')
    source: str | None = Field(None, description='Source registry identifier')
    command: list[str] | None = None
    args: list[str] | None = None
    env: dict[str, str] | None = None
    inputPorts: list[PortDef] | None = None
    outputPorts: list[PortDef] | None = None
    resources: PipelineComponentResources | None = None
    envVars: list[EnvVarDef] | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class PipelineComponentRequest(BaseModel):
    name: str
    type: Type
    description: str | None = None
    image: str
    tag: str | None = 'latest'
    source: str | None = 'custom'
    command: list[str] | None = None
    args: list[str] | None = None
    env: dict[str, str] | None = None
    inputPorts: list[PortDef] | None = None
    outputPorts: list[PortDef] | None = None
    resources: PipelineComponentResources | None = None
    envVars: list[EnvVarDef] | None = None


class PipelineConfig(BaseModel):
    id: str | None = None
    name: str | None = None
    description: str | None = None
    owner: str | None = None
    scope: str | None = 'dev'
    tags: list[str] | None = None
    fileType: FileType | None = None
    lifecycle: Lifecycle | None = None
    currentVersion: conint(ge=1) | None = None
    versionCount: conint(ge=0) | None = None
    versions: list[PipelineConfigVersion] | None = Field(
        None,
        description='Version summaries. File content is omitted here; fetch a specific version for content.',
    )
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class PipelineConfigListResponse(BaseModel):
    items: list[PipelineConfig] | None = None


class ComponentReleaseRuntimeSnapshot(BaseModel):
    image: str = Field(
        ...,
        description='Immutable runtime image, preferably pinned by digest.',
        examples=[
            'us-central1-docker.pkg.dev/my-project/video-proc-images/hand-detect-yolov26m@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
        ],
    )
    command: list[str] | None = None
    args: list[str] | None = None
    env: dict[str, str] | None = None
    inputPorts: list[PortDef]
    outputPorts: list[PortDef]
    resources: dict[str, Any] | None = None


class PipelineComponentRelease(BaseModel):
    id: str
    imageUid: str | None = Field(
        None,
        description='Stable 8-character DataBrew image ID generated from image digest, falling back to runtime image.',
        examples=['2f4a9c01'],
    )
    componentId: str
    taskName: str
    taskPath: str | None = None
    displayName: str | None = None
    owner: str | None = None
    releaseLabel: str = Field(
        ...,
        description='User-facing version label such as pr-128-abc123, main-abc123, v0.4.1-rc.1, or v0.4.0.',
    )
    channel: Channel
    sourceRepo: str | None = None
    sourceRef: str | None = None
    sourceRefType: SourceRefType | None = None
    sourceCommit: str | None = None
    buildId: str | None = None
    imageRepo: str | None = None
    imageTag: str | None = None
    imageDigest: str | None = None
    runtimeImage: str
    status: Status6
    selectable: bool
    validationStatus: ValidationStatus
    validationErrors: list[str] | None = None
    runtimeSnapshot: ComponentReleaseRuntimeSnapshot
    technicalMetadata: dict[str, Any] | None = None
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    lastSyncedAt: AwareDatetime | None = None


class PipelineComponentReleaseInput(BaseModel):
    id: str | None = None
    imageUid: str | None = Field(
        None,
        description='Optional CI-provided DataBrew image ID. DataBrew derives it from image digest when omitted.',
    )
    componentId: str | None = None
    taskName: str | None = None
    taskPath: str | None = None
    displayName: str | None = None
    owner: str | None = None
    releaseLabel: str | None = None
    channel: Channel | None = None
    sourceRepo: str | None = None
    sourceRef: str | None = None
    sourceRefType: SourceRefType | None = None
    sourceCommit: str | None = None
    buildId: str | None = None
    imageRepo: str | None = None
    imageTag: str | None = None
    imageDigest: str | None = None
    runtimeImage: str | None = None
    status: Status6 | None = None
    runtimeSnapshot: ComponentReleaseRuntimeSnapshot | None = None
    technicalMetadata: dict[str, Any] | None = None


class ComponentReleaseSyncRequest(BaseModel):
    source: ComponentReleaseIngestSource | None = None
    items: list[PipelineComponentReleaseInput]


class ComponentReleaseListResponse(BaseModel):
    items: list[PipelineComponentRelease] | None = None


class WorkflowNodeStatus(BaseModel):
    id: str | None = None
    name: str | None = None
    displayName: str | None = None
    type: str | None = Field(None, description='Node type (Pod, StepGroup, DAG, etc.)')
    templateName: str | None = None
    phase: str | None = Field(
        None, description='Node phase (Running, Succeeded, Failed, Error, etc.)'
    )
    message: str | None = None
    inputs: dict[str, Any] | None = Field(
        None, description='Argo node inputs, including parameters and artifacts.'
    )
    outputs: dict[str, Any] | None = Field(
        None, description='Argo node outputs, including parameters and artifacts.'
    )
    resourcesDuration: dict[str, Any] | None = Field(
        None, description='Argo resource duration counters for the node.'
    )
    hostNodeName: str | None = None
    podName: str | None = Field(
        None, description='Kubernetes pod name backing this Argo Pod node'
    )
    progress: str | None = Field(None, description='Node progress')
    estimatedDuration: int | None = Field(
        None, description='Estimated node duration in seconds'
    )
    children: list[str] | None = None
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    debug: WorkflowNodeDebugCapabilities | None = None


class WorkflowNodePodDiagnostics(BaseModel):
    cluster: str | None = Field(
        None, description='Optional Kubernetes cluster display label'
    )
    namespace: str = Field(..., description='Kubernetes namespace')
    podName: str = Field(
        ..., description='Kubernetes Pod name backing this workflow node'
    )
    podIp: str | None = Field(None, description='Kubernetes Pod IP')
    serviceAccountName: str | None = Field(None, description='Pod service account name')
    restartCount: int = Field(..., description='Sum of all container restart counts')
    containers: list[WorkflowNodePodContainer]
    podConditions: list[WorkflowNodePodCondition]
    podEvents: list[WorkflowNodePodEvent]


class RunChildList(BaseModel):
    runId: str | None = None
    items: list[PipelineRun] | None = None
    relations: list[RunRelation] | None = Field(
        None,
        description='Projected Run relations. Batch trees derive batch_child rows from child run metadata; rerun/resubmit/legacy retry rows can be projected from RunEvent ledger payloads until a relation table exists.',
    )
    summary: RunChildSummary | None = None
    total: int | None = None


class WorkflowDetail(BaseModel):
    name: str | None = None
    status: str | None = None
    message: str | None = None
    labels: dict[str, str] | None = None
    estimatedDuration: int | None = Field(
        None, description='Estimated workflow duration in seconds'
    )
    progress: str | None = Field(None, description='Workflow progress')
    nodes: list[WorkflowNodeStatus] | None = Field(
        None,
        description='Runtime workflow nodes plus static pending DAG task placeholders for not-yet-started tasks.',
    )
    edges: list[WorkflowDagEdge] | None = Field(
        None,
        description='Normalized workflow DAG edges between runtime nodes and static pending DAG task placeholders.',
    )
    createdAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
