"""Central registry of all API endpoint path templates.

Every endpoint path in the SDK is defined here — not scattered across
managers. This gives us a single source of truth that can be overridden
by any ConfigSource (env, file, remote).

Key: logical endpoint name (``{domain}_{action}``)
Value: URL path template (uses ``str.format`` for parameter substitution)
"""

ENDPOINTS: dict[str, str] = {
    # ── Assets ────────────────────────────────────────────────────────
    "asset_get": "/api/v1/assets/{asset_id}",
    "asset_list": "/api/v1/assets",
    "asset_create": "/api/v1/assets",
    "asset_update": "/api/v1/assets/{asset_id}",
    "asset_delete": "/api/v1/assets/{asset_id}",
    "asset_batch_get": "/api/v1/assets:batch_get",
    "asset_tags_list": "/api/v1/assets/{asset_id}/tags",
    "asset_tags_set": "/api/v1/assets/{asset_id}/tags",
    "asset_tags_get": "/api/v1/assets/{asset_id}/tags/{key}",
    "asset_tags_delete": "/api/v1/assets/{asset_id}/tags/{key}",
    "asset_tags_history": "/api/v1/assets/{asset_id}/tags/history",
    "asset_lineage": "/api/v1/assets/{asset_id}/lineage",
    "asset_provenance": "/api/v1/assets/{asset_id}/provenance",
    "asset_timeline": "/api/v1/assets/{asset_id}/timeline",
    "asset_mcap_locator": "/api/v1/assets/{asset_id}/mcap-locator",
    "asset_foxglove_source": "/api/v1/assets/{asset_id}/foxglove-source",
    "asset_deliveries": "/api/v1/assets/{asset_id}/deliveries",
    "asset_events": "/api/v1/assets/{asset_id}/events",
    "asset_record_view": "/api/v1/assets/{asset_id}/view",
    "asset_set_favorite": "/api/v1/assets/{asset_id}/favorite",
    "asset_revisions": "/api/v1/assets/{asset_id}/revisions",
    # ── Storage / MCAP ────────────────────────────────────────────────
    "storage_files_list": "/api/v1/mcap-files",
    "storage_file_info": "/api/v1/mcap-files/{mcap_id}",
    "storage_mcap_download": "/api/v1/mcap-files/{mcap_file_id}/bytes",
    "storage_upload_finalize": "/api/v1/mcap/upload/finalize",
    "storage_mcap_messages": "/api/v1/mcap/{mcap_id}/messages",
    # ── Delivery ──────────────────────────────────────────────────────
    "delivery_get": "/api/v1/deliveries/{delivery_id}",
    "delivery_list": "/api/v1/deliveries",
    "delivery_create": "/api/v1/deliveries",
    "delivery_draft": "/api/v1/deliveries/draft",
    "delivery_commit": "/api/v1/deliveries/{delivery_id}/commit",
    "delivery_cancel": "/api/v1/deliveries/{delivery_id}/cancel",
    "delivery_retry": "/api/v1/deliveries/{delivery_id}/retry",
    "delivery_ack": "/api/v1/deliveries/{delivery_id}/ack",
    "delivery_items_list": "/api/v1/deliveries/{delivery_id}/items",
    "delivery_items_add": "/api/v1/deliveries/{delivery_id}/items",
    "delivery_customer_list": "/api/v1/customers/{customer_id}/deliveries",
    "delivery_rules_list": "/api/v1/delivery-rules",
    "delivery_rules_create": "/api/v1/delivery-rules",
    # ── Algo Runs ─────────────────────────────────────────────────────
    "algo_run_get": "/api/v1/algo-runs/{run_id}",
    "algo_run_list": "/api/v1/algo-runs",
    "algo_run_create": "/api/v1/algo-runs",
    "algo_run_start": "/api/v1/algo-runs/{run_id}/start",
    "algo_run_finish": "/api/v1/algo-runs/{run_id}/finish",
    "algo_run_cancel": "/api/v1/algo-runs/{run_id}/cancel",
    "algo_run_affected_assets": "/api/v1/algo-runs/{run_id}/affected-assets",
    # ── Search ────────────────────────────────────────────────────────
    "search_assets": "/api/v1/search/assets",
    "search_sync_status": "/api/v1/search/sync-status",
    "search_sync_progress": "/api/v1/search/sync-progress",
    # ── Queries ───────────────────────────────────────────────────────
    "query_validate": "/api/v1/queries/validate",
    "query_run": "/api/v1/queries/run",
    "query_saved_list": "/api/v1/saved-queries",
    "query_saved_get": "/api/v1/saved-queries/{query_id}",
    "query_saved_create": "/api/v1/saved-queries",
    "query_saved_update": "/api/v1/saved-queries/{query_id}",
    "query_saved_delete": "/api/v1/saved-queries/{query_id}",
    # ── Customers ─────────────────────────────────────────────────────
    "customer_list": "/api/v1/customers",
    "customer_get": "/api/v1/customers/{customer_id}",
    "customer_create": "/api/v1/customers",
    "customer_update": "/api/v1/customers/{customer_id}",
    # ── Lakehouse ─────────────────────────────────────────────────────
    "lakehouse_report": "/api/v1/lakehouse/report",
    "lakehouse_status": "/api/v1/lakehouse/status",
    "lakehouse_tables": "/api/v1/lakehouse/tables",
    "lakehouse_overview": "/api/v1/lakehouse/overview",
    "lakehouse_event_daily": "/api/v1/lakehouse/event-daily",
    "lakehouse_event_type_share": "/api/v1/lakehouse/event-type-share",
    "lakehouse_asset_growth": "/api/v1/lakehouse/asset-growth",
    "lakehouse_sync_status": "/api/v1/lakehouse/sync-status",
    "lakehouse_sync_progress": "/api/v1/lakehouse/sync-progress",
    "lakehouse_failure_clusters": "/api/v1/lakehouse/failure-clusters",
    "lakehouse_quality_distribution": "/api/v1/lakehouse/quality-distribution",
    "lakehouse_customer_replay": "/api/v1/lakehouse/customer-replay",
    # ── Events ────────────────────────────────────────────────────────
    "event_list": "/api/v1/events",
    "event_list_asset": "/api/v1/assets/{asset_id}/events",
    "event_stream_asset": "/api/v1/assets/{asset_id}/events/stream",
    # ── Registry ──────────────────────────────────────────────────────
    "registry_algos": "/api/v1/algo-registry",
    "registry_tags": "/api/v1/tag-registry",
    "registry_metrics": "/api/v1/metric-registry",
    "registry_action_labels": "/api/v1/action-label-registry",
    "registry_lifecycle_states": "/api/v1/lifecycle-states",
    # ── Audit ─────────────────────────────────────────────────────────
    "audit_search": "/api/v1/audit/search",
    "audit_lineage_search": "/api/v1/audit/lineage-search",
    # ── Actions (child assets) ─────────────────────────────────────────
    "action_list": "/api/v1/assets/{asset_id}/actions",
    "action_create": "/api/v1/assets/{asset_id}/actions",
    "action_update": "/api/v1/assets/{asset_id}/actions/{action_id}",
    "action_delete": "/api/v1/assets/{asset_id}/actions/{action_id}",
    # ── Eval / Metrics ────────────────────────────────────────────────
    "eval_result_report": "/api/v1/assets/{asset_id}/eval-results",
    "eval_result_list": "/api/v1/assets/{asset_id}/eval-results",
    "metric_list": "/api/v1/assets/{asset_id}/metrics",
    "metric_registry": "/api/v1/metrics/registry",
    "metric_search": "/api/v1/metrics:search",
    # ── Admin / Search Reindex ─────────────────────────────────────────
    "admin_search_reindex": "/api/v1/admin/search/reindex",
    "admin_search_reindex_job_create": "/api/v1/admin/search/reindex-jobs",
    "admin_search_reindex_job_list": "/api/v1/admin/search/reindex-jobs",
    "admin_search_reindex_job_get": "/api/v1/admin/search/reindex-jobs/{job_id}",
    "admin_search_reindex_job_stop": "/api/v1/admin/search/reindex-jobs/{job_id}/stop",
    "admin_search_reindex_job_resume": "/api/v1/admin/search/reindex-jobs/{job_id}/resume",
    "admin_search_reindex_job_abandon": "/api/v1/admin/search/reindex-jobs/{job_id}/abandon",
    # ── Workflows ─────────────────────────────────────────────────────
    "workflow_list": "/api/v1/workflows",
    "workflow_get": "/api/v1/workflows/{workflow_name}",
    "workflow_logs": "/api/v1/workflows/{workflow_name}/logs",
    "workflow_terminal_create": "/api/v1/workflows/{workflow_name}/nodes/{node_id}/terminal-sessions",
    "pod_terminal_session_get": "/api/v1/pod-terminal/sessions/{session_id}",
    "pod_terminal_session_terminate": "/api/v1/pod-terminal/sessions/{session_id}/terminate",
    "pod_terminal_session_attach": "/api/v1/pod-terminal/sessions/{session_id}/attach",
    "workflow_retry": "/api/v1/workflows/{workflow_name}/retry",
    "workflow_resubmit": "/api/v1/workflows/{workflow_name}/resubmit",
    "workflow_suspend": "/api/v1/workflows/{workflow_name}/suspend",
    "workflow_resume": "/api/v1/workflows/{workflow_name}/resume",
    "workflow_terminate": "/api/v1/workflows/{workflow_name}/terminate",
    "workflow_delete": "/api/v1/workflows/{workflow_name}",
    # ── Pipelines ─────────────────────────────────────────────────────
    "pipeline_execution_targets": "/api/v1/execution-targets",
    "pipeline_runtime_mounts": "/api/v1/pipeline/runtime-mounts",
    "pipeline_run_create": "/api/v1/pipeline-runs",
    "pipeline_run_create_template": "/api/v1/pipeline-runs/template/{template_id}",
    "pipeline_run_list": "/api/v1/pipeline-runs",
    "pipeline_run_get": "/api/v1/pipeline-runs/{run_id}",
    "pipeline_run_watcher_status": "/api/v1/pipeline-runs/watcher/status",
    "pipeline_run_events": "/api/v1/pipeline-runs/{run_id}/events",
    "pipeline_run_asset_nodes": "/api/v1/pipeline-runs/{run_id}/asset-nodes",
    "pipeline_run_cost_summary": "/api/v1/pipeline-runs/{run_id}/cost-summary",
    "pipeline_run_retry": "/api/v1/pipeline-runs/{run_id}/retry",
    "pipeline_run_stop": "/api/v1/pipeline-runs/{run_id}/stop",
    "pipeline_run_delete": "/api/v1/pipeline-runs/{run_id}",
    "pipeline_deploy_template": "/api/v1/deploy/template/{template_id}",
    "pipeline_deployment_list": "/api/v1/deployments",
    # ── Runs (product execution API) ──────────────────────────────────
    "run_create": "/api/v1/runs",
    "run_create_template": "/api/v1/runs/template/{template_id}",
    "run_list": "/api/v1/runs",
    "run_get": "/api/v1/runs/{run_id}",
    "run_by_workflow": "/api/v1/runs/by-workflow/{workflow_name}",
    "run_watcher_status": "/api/v1/runs/watcher/status",
    "run_events": "/api/v1/runs/{run_id}/events",
    "run_nodes": "/api/v1/runs/{run_id}/nodes",
    "run_asset_nodes": "/api/v1/runs/{run_id}/asset-nodes",
    "run_cost_summary": "/api/v1/runs/{run_id}/cost-summary",
    "run_inputs": "/api/v1/runs/{run_id}/inputs",
    "run_outputs": "/api/v1/runs/{run_id}/outputs",
    "run_children": "/api/v1/runs/{run_id}/children",
    "run_runtime": "/api/v1/runs/{run_id}/runtime",
    "run_retry": "/api/v1/runs/{run_id}/retry",
    "run_resubmit": "/api/v1/runs/{run_id}/resubmit",
    "run_rerun": "/api/v1/runs/{run_id}/rerun",
    "run_stop": "/api/v1/runs/{run_id}/stop",
    "run_suspend": "/api/v1/runs/{run_id}/suspend",
    "run_resume": "/api/v1/runs/{run_id}/resume",
    "run_terminate": "/api/v1/runs/{run_id}/terminate",
    "run_delete": "/api/v1/runs/{run_id}",
    # ── Pipeline Configs ──────────────────────────────────────────────
    "pipeline_config_list": "/api/v1/pipeline-configs",
    "pipeline_config_create": "/api/v1/pipeline-configs",
    "pipeline_config_get": "/api/v1/pipeline-configs/{config_id}",
    "pipeline_config_update": "/api/v1/pipeline-configs/{config_id}",
    "pipeline_config_version_create": "/api/v1/pipeline-configs/{config_id}/versions",
    "pipeline_config_version_get": "/api/v1/pipeline-configs/{config_id}/versions/{version}",
    "pipeline_config_deprecate": "/api/v1/pipeline-configs/{config_id}/deprecate",
    # ── Pipeline Components ────────────────────────────────────────────
    "pipeline_component_list": "/api/v1/pipeline-components",
    "pipeline_component_create": "/api/v1/pipeline-components",
    "pipeline_component_get": "/api/v1/pipeline-components/{component_id}",
    "pipeline_component_update": "/api/v1/pipeline-components/{component_id}",
    "pipeline_component_delete": "/api/v1/pipeline-components/{component_id}",
    "pipeline_component_release_list": "/api/v1/pipeline-component-releases",
    "pipeline_component_release_get": "/api/v1/pipeline-component-releases/{release_id}",
    "pipeline_component_release_sync": "/api/v1/pipeline-component-releases/sync",
    # ── SDK Config (bootstrap discovery) ──────────────────────────────
    "sdk_config": "/api/v1/sdk-config",
}
