// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets": {
            "post": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Create a new asset segment from an MCAP file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Create asset",
                "parameters": [
                    {
                        "description": "Create asset request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Asset"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets/{id}": {
            "get": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Get asset by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Get asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Asset"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Soft delete an asset (status = archived)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Delete asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets/{id}/algo/{algo_key}/finish": {
            "post": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Mark an algorithm as ok or failed on the given asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "algorithms"
                ],
                "summary": "Finish algorithm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Algorithm key (name@version)",
                        "name": "algo_key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Finish algo request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets/{id}/algo/{algo_key}/reset": {
            "post": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Reset a failed or ok algorithm back to pending state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "algorithms"
                ],
                "summary": "Reset algorithm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Algorithm key (name@version)",
                        "name": "algo_key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets/{id}/algo/{algo_key}/start": {
            "post": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Mark an algorithm as running on the given asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "algorithms"
                ],
                "summary": "Start algorithm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Algorithm key (name@version)",
                        "name": "algo_key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Start algo request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets/{id}/events": {
            "get": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "List generic asset events with optional event_type/algo_key filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List asset events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Repeated event type filter; supports wildcard suffix like algo_*",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter event_payload.algo_key",
                        "name": "algo_key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Fetch older events with event_seq \u003c cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Alias of cursor",
                        "name": "before_event_seq",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Fetch events with event_seq \u003e after_event_seq",
                        "name": "after_event_seq",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Lower bound of occurred_at (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Upper bound of occurred_at (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets/{id}/tags": {
            "post": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Create or update one tag entry under asset_tags and append tag_upserted",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Upsert asset tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tag upsert request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Asset"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets/{id}/tags/history": {
            "get": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "List tag-specific events sourced from asset_events",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List asset tag history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Fetch older events with event_seq \u003c cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Alias of cursor",
                        "name": "before_event_seq",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Fetch events with event_seq \u003e after_event_seq",
                        "name": "after_event_seq",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets/{id}/tags/{key}": {
            "delete": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Delete one tag entry under asset_tags and append tag_deleted when present",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Delete asset tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tag key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Asset"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/assets:batch_get": {
            "post": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Retrieve multiple assets by ID in a single request (max 100)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Batch get assets",
                "parameters": [
                    {
                        "description": "Batch get request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        },
        "/deliveries": {
            "post": {
                "security": [
                    {
                        "GraceToken": []
                    }
                ],
                "description": "Create a new delivery for a set of assets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deliveries"
                ],
                "summary": "Commit delivery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Commit delivery request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresp.ErrorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpresp.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "models.Asset": {
            "type": "object",
            "properties": {
                "algo_results": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "asset_id": {
                    "description": "Identity",
                    "type": "string"
                },
                "asset_level": {
                    "type": "integer"
                },
                "asset_type": {
                    "description": "── NEW typed fields (Phase 2 — schema evolution) ────────────────────",
                    "type": "string"
                },
                "created_at": {
                    "description": "Timestamps / versioning",
                    "type": "string"
                },
                "delivery_count": {
                    "type": "integer"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "duration_sec": {
                    "type": "number"
                },
                "end_timestamp_ns": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "expire_at": {
                    "type": "string"
                },
                "files": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "files_json": {
                    "type": "object",
                    "additionalProperties": true
                },
                "last_delivered_at": {
                    "type": "string"
                },
                "last_delivered_to": {
                    "type": "string"
                },
                "lifecycle_meta": {
                    "type": "object",
                    "additionalProperties": true
                },
                "lifecycle_state": {
                    "type": "string"
                },
                "mcap_file_id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "owner": {
                    "type": "string"
                },
                "parent_asset_id": {
                    "type": "string"
                },
                "parent_end_offset_ms": {
                    "type": "integer"
                },
                "parent_start_offset_ms": {
                    "type": "integer"
                },
                "project_id": {
                    "type": "string"
                },
                "retention_tier": {
                    "type": "string"
                },
                "reviewer": {
                    "type": "string"
                },
                "root_asset_id": {
                    "type": "string"
                },
                "segment_index": {
                    "type": "integer"
                },
                "segment_locator": {
                    "description": "Segment locator — deterministic SHA-1 of mcap_file_id + start_ns + end_ns.",
                    "type": "string"
                },
                "split_algo_name": {
                    "type": "string"
                },
                "split_algo_version": {
                    "type": "string"
                },
                "split_method": {
                    "type": "string"
                },
                "split_reason": {
                    "type": "string"
                },
                "split_run_id": {
                    "type": "string"
                },
                "start_timestamp_ns": {
                    "description": "── Legacy fields (retained for backward compatibility) ──────────────",
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.AssetStatus"
                },
                "storage_uri": {
                    "type": "string"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "task": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "thumb_uri": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "models.AssetStatus": {
            "type": "string",
            "enum": [
                "approved",
                "rejected",
                "superseded",
                "archived"
            ],
            "x-enum-varnames": [
                "AssetStatusApproved",
                "AssetStatusRejected",
                "AssetStatusSuperseded",
                "AssetStatusArchived"
            ]
        }
    },
    "securityDefinitions": {
        "GraceToken": {
            "type": "apiKey",
            "name": "X-Grace-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Data Platform API",
	Description:      "Backend API for the Data Platform (asset, algo, delivery, mcap management).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
