apiVersion: v1
kind: ConfigMap
metadata:
  name: cyber-databrew-grafana-datasource
  labels:
    app.kubernetes.io/name: cyber-databrew-monitoring
    app.kubernetes.io/component: grafana
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://cyber-databrew-prometheus:9090
        isDefault: true
        editable: false
