apiVersion: v1
kind: Service
metadata:
  name: cyber-databrew-grafana
  labels:
    app.kubernetes.io/name: cyber-databrew-monitoring
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cyber-databrew-monitoring
    app.kubernetes.io/component: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
