apiVersion: v1
kind: Service
metadata:
  name: cyber-databrew-prometheus
  labels:
    app.kubernetes.io/name: cyber-databrew-monitoring
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cyber-databrew-monitoring
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
