apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-developer-gateway-monitoring
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: developer-gateway
  to:
    - group: ""
      kind: Service
      name: cyber-databrew-grafana
    - group: ""
      kind: Service
      name: cyber-databrew-prometheus
