output "frontend_dns_challenge" {
  description = "Frontend ACME DNS record generated by Certificate Manager."
  value       = google_certificate_manager_dns_authorization.frontend.dns_resource_record
}

output "api_dns_challenge" {
  description = "API ACME DNS record generated by Certificate Manager."
  value       = google_certificate_manager_dns_authorization.api.dns_resource_record
}

output "frontend_certificate_state" {
  description = "Frontend certificate managed state."
  value       = google_certificate_manager_certificate.frontend.managed[0].state
}

output "api_certificate_state" {
  description = "API certificate managed state."
  value       = google_certificate_manager_certificate.api.managed[0].state
}
