substitutions:
  _BASE_IMAGE: us-central1-docker.pkg.dev/green-valley-442103/video-proc-images/cyber-databrew-frontend:dev-latest
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/cloudrun/frontend-cloudrun.Dockerfile
      - --build-arg
      - BASE_IMAGE=$_BASE_IMAGE
      - -t
      - $_IMAGE
      - .
images:
  - $_IMAGE
