apiVersion: v1
kind: Service
metadata:
  name: mcap-preview
  labels:
    app.kubernetes.io/name: mcap-preview
    app.kubernetes.io/component: preview
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mcap-preview
    app.kubernetes.io/component: preview
  ports:
    - name: http
      port: 8090
      targetPort: http
