#!/usr/bin/env python3
"""Generate mkdocs.yml from docs/repo-wiki/manifest.yaml.

The manifest is the single source of truth for the wiki's structure; this script
projects it into a Material for MkDocs config (nav tree grouped by `section`,
in manifest order). Re-run whenever the manifest changes.

Usage:
    python3 scripts/repo-wiki/gen_mkdocs.py [--out mkdocs.yml]

Then:
    pip install mkdocs-material
    mkdocs serve            # http://localhost:8000
    mkdocs build            # -> docs/repo-wiki-site/ (gitignored)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs" / "repo-wiki"
MANIFEST = DOCS_DIR / "manifest.yaml"

# Static config head. docs_dir/site_dir are relative to the mkdocs.yml location
# (repo root). The nav: block is appended by this script from the manifest.
CONFIG_HEAD = """# GENERATED by scripts/repo-wiki/gen_mkdocs.py from docs/repo-wiki/manifest.yaml — do not edit by hand.
# Source of truth is the markdown under docs/repo-wiki/. Re-run the generator after editing the manifest.
site_name: {site_name}
site_description: cyber-databrew repository wiki
docs_dir: docs/repo-wiki
site_dir: docs/repo-wiki-site
use_directory_urls: true
exclude_docs: |
  manifest.yaml
not_in_nav: |
  /README.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

hooks:
  - scripts/repo-wiki/mkdocs_hooks.py

nav:
"""


def load_manifest():
    try:
        import yaml
    except ImportError:
        print("error: PyYAML required: pip install pyyaml", file=sys.stderr)
        sys.exit(1)
    if not MANIFEST.exists():
        print(f"error: manifest not found: {MANIFEST}", file=sys.stderr)
        sys.exit(1)
    data = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
    return data.get("title", "Repository Wiki"), data.get("pages", [])


def esc(s: str) -> str:
    # quote nav titles that contain YAML-significant chars
    if any(c in s for c in ":#&*!|>'\"%@`{}[],") or s.strip() != s:
        return '"' + s.replace('"', '\\"') + '"'
    return s


def build_nav(pages) -> str:
    """Emit a YAML nav list grouped by section (and optional subsection), in manifest order.

    Two grouping levels are supported via `section` and `subsection`:
      section -> "  - {section}:"            (a page with no section is top-level)
        page  -> "      - {title}: {path}"
        subsection -> "      - {subsection}:" (opens at its first page)
          page -> "          - {title}: {path}"
    Pages sharing a subsection must be contiguous within their section.
    """
    lines = ["  - Home: README.md"]
    current_section = None
    current_subsection = None
    for p in pages:
        title, path = p.get("title"), p.get("path")
        section, subsection = p.get("section"), p.get("subsection")
        if not path:
            continue
        if section != current_section:
            current_section = section
            current_subsection = None
            if section:
                lines.append(f"  - {esc(section)}:")
        if section and subsection:
            if subsection != current_subsection:
                current_subsection = subsection
                lines.append(f"      - {esc(subsection)}:")
            lines.append(f"          - {esc(title)}: {path}")
        elif section:
            current_subsection = None
            lines.append(f"      - {esc(title)}: {path}")
        else:
            lines.append(f"  - {esc(title)}: {path}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "mkdocs.yml")
    args = ap.parse_args()

    site_name, pages = load_manifest()
    config = CONFIG_HEAD.format(site_name=esc(site_name)) + build_nav(pages)
    args.out.write_text(config, encoding="utf-8")
    print(f"wrote {args.out} ({len(pages)} pages)")
    print("next: pip install mkdocs-material && mkdocs serve")


if __name__ == "__main__":
    main()
