package config

import (
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/joho/godotenv"

	"github.com/CyberOrigin2077/cyber-databrew/internal/transpiler"
)

type Config struct {
	Env             string
	Port            string
	McapGatewayPort string
	DeliveryPort    string

	// Storage backend: postgres (default)
	StorageBackend string

	// PostgreSQL
	DBHost     string
	DBPort     string
	DBUser     string
	DBPassword string
	DBName     string

	// GCS (optional, for future derived artifacts)
	GCSProject       string
	GCSDerivedBucket string

	// Pub/Sub
	PubSubProject      string
	TopicMcapFinalized string
	TopicAssetEvents   string

	// Auth (Phase 0 static token; Phase 0.5 → email + JWT)
	DatabrewToken               string
	ComponentReleaseIngestToken string   // CI-only token for component release ingest
	JWTSecret                   string   // HMAC-SHA256 secret for JWT signing
	AllowedDomain               string   // email domain allowlisted (e.g. "cyberorigin.ai")
	AdminEmails                 []string // emails granted role=admin on email-login (ADMIN_EMAILS, comma-sep)

	// Logging
	LogLevel  string // debug, info, warn, error
	LogFormat string // text, json
	LogFile   string // file path (empty = stdout only)

	// Rate Limiting (per IP)
	RateLimitRPS   string // requests per second (0 = disabled)
	RateLimitBurst string // burst size (default = RPS * 2)

	// Circuit Breaker
	CBEnabled     string // "true" to enable
	CBWindowSec   string // sliding window seconds (default: 60)
	CBThreshold   string // error count to trip (default: 10)
	CBCooldownSec string // cooldown seconds (default: 30)

	// Local lakehouse MVP report generated by deploy/local/iceberg/notebooks/build_lakehouse_mvp.py.
	LakehouseReportPath string

	// Lakehouse analytical query layer.
	//
	// LakehouseBackend selects the engine: "bigquery" (default) reads
	// BigLake-managed Iceberg via BigQuery external tables; "none" disables
	// the layer entirely. Trino is no longer supported — see
	// docs/adr/001-iceberg-catalog-selection.md.
	LakehouseBackend   string
	LakehouseBQProject string // GCP project hosting the BigQuery dataset
	LakehouseBQDataset string // dataset containing Iceberg external tables (e.g. lakehouse_bronze)

	// Elasticsearch
	ElasticsearchURL      string
	ElasticsearchUsername string // optional; defaults to "elastic" when ElasticsearchPassword is set
	ElasticsearchPassword string // optional; HTTP Basic auth to ES when non-empty

	// Outbox relay (PG asset_events → Pub/Sub) and ES subscriber (Pub/Sub → Elasticsearch).
	OutboxRelayEnabled        string
	OutboxRelayBatchSize      string
	OutboxRelayIntervalMs     string
	OutboxRelaySafetyLagSec   string
	OutboxRelayLeaseSec       string
	OutboxRelayMaxRetries     string
	OutboxProgressLogInterval string // seconds; 0 disables periodic relay progress logs
	OutboxESSubscriberEnabled string
	OutboxESSubscription      string // subscription id in PubSubProject (short name)
	OutboxTransport           string // internal | pubsub | kafka (default internal)
	OutboxKafkaBrokers        string // comma-separated brokers for kafka mode
	OutboxKafkaTopic          string // topic for kafka mode (fallback: TOPIC_ASSET_EVENTS)
	OutboxKafkaGroupID        string // consumer group for ES subscriber in kafka mode

	// OUTBOX_TRANSPORT=internal only: parallel ES handlers (per routing key serial).
	OutboxInternalSubscriberWorkers string
	// OUTBOX_TRANSPORT=internal only: in-memory bus channel buffer (matches the
	// historical NewInMemoryBus(1024) constant). Larger buffers absorb relay
	// bursts without back-pressuring the publisher.
	OutboxInternalBusBuffer string
	// OUTBOX_TRANSPORT=internal only: maximum events coalesced into a single ES
	// _bulk request per worker. 1 disables batching (legacy single-doc path).
	OutboxInternalSubscriberBatchSize string
	// OUTBOX_TRANSPORT=internal only: how long a worker is allowed to wait after
	// the first message arrives before flushing a partial batch. 0 means
	// "flush whatever is already in the channel without waiting".
	OutboxInternalSubscriberBatchWaitMs string
	// Max concurrent ordering-key groups in one relay flush (different keys run in parallel).
	OutboxRelayParallelKeys string

	// OutboxESCheckpointShards is the modulus for the es_sync_checkpoint table.
	// Each successful ES bulk emits at most "shards-in-batch" UPSERTs into this
	// table; the cross-shard MIN(applied_seq) is exposed as consumer_lag in
	// /api/v1/search/sync-progress. Larger values give finer-grained MIN
	// (less stale-shard drag) at the cost of more rows; 16 is a reasonable
	// default. Must be <= 1024.
	OutboxESCheckpointShards string

	// OutboxESCheckpointIdleAfterSec treats a checkpoint row as "caught up" for
	// MIN(applied_seq) purposes when its updated_at is older than this many
	// seconds. Without this, a low-traffic shard whose applied_seq legitimately
	// lags PG's max would drag consumer_lag up forever. 0 disables (legacy
	// behavior: raw MIN over all rows). 300s (5 min) matches a typical relay
	// poll cycle + ES bulk window.
	OutboxESCheckpointIdleAfterSec string

	// Admin endpoints (search reindex, etc.). Empty disables routes.
	AdminToken string

	// FacetEngine (CYB-3384): "auto" (default) lets the planner pick between
	// ES (fast, prod) and PG (strong-consistent, drift fallback) based on the
	// live pg_es_gap. "es" forces the legacy ES aggregation path. "pg" forces
	// the PostgreSQL GROUP BY path — useful when ES is misindexed or offline.
	FacetEngine string

	// OpenLineage emitter
	OpenLineageEmitterEnabled string
	OpenLineageEndpoint       string
	OpenLineageSubscription   string
	OpenLineageNamespace      string
	OpenLineageProducer       string
	OpenLineageTimeoutMs      string

	// Argo Workflows
	ArgoWorkflowsNamespace                string
	ArgoWorkflowTTLSecondsAfterCompletion int32
	// RuntimeConfigTTLDays ages content-addressed runtime-config ConfigMaps
	// via the sliding-reference janitor (CYB-3680). Must exceed the workflow
	// TTL so Argo-native retries never re-mount a reclaimed CM.
	RuntimeConfigTTLDays int32
	// BatchDispatchMode selects the batch dispatch path (CYB-3677):
	// "submitter" (default) persists jobs for the durable backfill submitter;
	// "legacy" restores the pre-3677 in-memory goroutine (rollback only).
	BatchDispatchMode                     string
	PipelineResourceMaxCPU                string
	PipelineResourceMaxMemory             string
	PipelineResourceMaxDisk               string
	PipelineResourceMaxGPU                string
	PipelineUnschedulablePendingThreshold string

	// Argo run status push webhook (CYB-3058).
	// ArgoExitHookEnabled gates exit-hook injection into workflows (CYB-3681).
	// Default false: the bulk-pull watcher is the writeback path and each
	// exit-notify pod costs real money at batch scale. The inbound webhook
	// ENDPOINT stays registered either way (transition safety).
	ArgoExitHookEnabled bool
	// ArgoRunWebhookURL empty disables exit-hook injection (poll-only fallback).
	ArgoRunWebhookURL             string
	ArgoRunWebhookToken           string // backend-side token to validate inbound webhook calls
	ArgoRunWebhookTokenSecretName string // K8s Secret name referenced by the workflow hook env
	ArgoRunWebhookTokenSecretKey  string // key within that Secret
	ArgoRunWebhookImage           string // container image (with curl) for the exit-notify handler

	// Batch job completion Feishu notification (CYB-3071).
	// BackfillNotifyFeishuWebhookURL empty disables the notification entirely.
	BackfillNotifyFeishuWebhookURL string
	// FrontendBaseURL builds links in notification messages. Not tied to any
	// single notification feature; empty omits the link rather than erroring.
	FrontendBaseURL string

	// Run status watcher (now a reconcile backstop behind the push path).
	PipelineRunWatcherIntervalSec int32
	PipelineRunWatcherScanLimit   int32

	// Batch job reconcile backstop (CYB-3078): finalizes + notifies batch jobs
	// whose children finished, independent of the exit hook or a page open.
	BackfillReconcileIntervalSec int32
	BackfillReconcileScanLimit   int32

	// DeliveryEligibilityProjector
	DeliveryEligibilityProjectorEnabled string

	// PricingConfigPath points to the GCP pricing YAML for cost estimation.
	// Empty means cost estimation is skipped.
	PricingConfigPath string

	// Grace API (CYB-3072). Reusable client config; video-duration sync is the
	// first consumer. Empty URL/creds disables the Grace sync loop entirely.
	GraceAPIURL                  string
	GraceUsername                string
	GracePassword                string // plain or JSON {"AUTH_PASSWORD":...} from grace-api-dev
	VideoDurationSyncIntervalSec int32
}

func Load() *Config {
	// Optional explicit env file for runtime config aggregation.
	// This is useful in Cloud Run / CI when operators want a single config file
	// (PG/ES/Trino/etc.) without relying on a local .env in cwd.
	if envFile := os.Getenv("BACKEND_ENV_FILE"); envFile != "" {
		_ = godotenv.Overload(envFile)
	}

	return &Config{
		Env:             getenv("ENV", "development"),
		Port:            getenv("PORT", "8080"),
		McapGatewayPort: getenv("MCAP_GATEWAY_PORT", "8081"),
		DeliveryPort:    getenv("DELIVERY_PORT", "8082"),
		StorageBackend:  getenv("STORAGE_BACKEND", "postgres"),

		DBHost:     getenv("DB_HOST", "localhost"),
		DBPort:     getenv("DB_PORT", "5432"),
		DBUser:     getenv("DB_USER", "postgres"),
		DBPassword: getenv("DB_PASSWORD", "postgres"),
		DBName:     getenv("DB_NAME", "cyber_databrew_dev"),

		GCSProject:       getenv("GCS_PROJECT", ""),
		GCSDerivedBucket: getenv("GCS_DERIVED_BUCKET", "grace-derived"),

		PubSubProject:      getenv("PUBSUB_PROJECT", ""),
		TopicMcapFinalized: getenv("TOPIC_MCAP_FINALIZED", "gcs.mcap.finalized.v1"),
		TopicAssetEvents:   getenv("TOPIC_ASSET_EVENTS", "cyber-databrew-asset-events"),

		DatabrewToken:               getenv("DATABREW_TOKEN", getenv("GRACE_TOKEN", "dev-token")),
		ComponentReleaseIngestToken: getenv("COMPONENT_RELEASE_INGEST_TOKEN", getenv("DATABREW_CI_INGEST_TOKEN", "")),
		JWTSecret:                   getenv("JWT_SECRET", "dev-jwt-secret"),
		AllowedDomain:               getenv("ALLOWED_DOMAIN", "cyberorigin.ai"),
		AdminEmails:                 splitCSVLower(getenv("ADMIN_EMAILS", "")),

		LogLevel:  getenv("LOG_LEVEL", "info"),
		LogFormat: getenv("LOG_FORMAT", "text"),
		LogFile:   getenv("LOG_FILE", ""),

		RateLimitRPS:   getenv("RATE_LIMIT_RPS", "0"),
		RateLimitBurst: getenv("RATE_LIMIT_BURST", "0"),

		CBEnabled:     getenv("CB_ENABLED", "false"),
		CBWindowSec:   getenv("CB_WINDOW_SEC", "60"),
		CBThreshold:   getenv("CB_THRESHOLD", "10"),
		CBCooldownSec: getenv("CB_COOLDOWN_SEC", "30"),

		LakehouseReportPath: getenv("LAKEHOUSE_REPORT_PATH", "../deploy/local/iceberg/notebooks/lakehouse_report.json"),

		LakehouseBackend:   getenv("LAKEHOUSE_BACKEND", "bigquery"),
		LakehouseBQProject: getenv("LAKEHOUSE_BQ_PROJECT", getenv("GCS_PROJECT", "")),
		LakehouseBQDataset: getenv("LAKEHOUSE_BQ_DATASET", "lakehouse_bronze"),

		ElasticsearchURL:      getenv("ELASTICSEARCH_URL", "http://localhost:9200"),
		ElasticsearchUsername: getenv("ELASTICSEARCH_USERNAME", ""),
		ElasticsearchPassword: getenv("ELASTICSEARCH_PASSWORD", ""),

		OutboxRelayEnabled:        getenv("OUTBOX_RELAY_ENABLED", "false"),
		OutboxRelayBatchSize:      getenv("OUTBOX_RELAY_BATCH_SIZE", "200"),
		OutboxRelayIntervalMs:     getenv("OUTBOX_RELAY_INTERVAL_MS", "500"),
		OutboxRelaySafetyLagSec:   getenv("OUTBOX_RELAY_SAFETY_LAG_SEC", "2"),
		OutboxRelayLeaseSec:       getenv("OUTBOX_RELAY_LEASE_SEC", "30"),
		OutboxRelayMaxRetries:     getenv("OUTBOX_RELAY_MAX_RETRIES", "20"),
		OutboxProgressLogInterval: getenv("OUTBOX_PROGRESS_LOG_INTERVAL_SEC", "60"),
		OutboxESSubscriberEnabled: getenv("OUTBOX_ES_SUBSCRIBER_ENABLED", "false"),
		OutboxESSubscription:      getenv("OUTBOX_ES_SUBSCRIPTION", ""),
		OutboxTransport:           getenv("OUTBOX_TRANSPORT", "internal"),
		OutboxKafkaBrokers:        getenv("OUTBOX_KAFKA_BROKERS", ""),
		OutboxKafkaTopic:          getenv("OUTBOX_KAFKA_TOPIC", ""),
		OutboxKafkaGroupID:        getenv("OUTBOX_KAFKA_GROUP_ID", "cyber-databrew-outbox-es"),

		OutboxInternalSubscriberWorkers:     getenv("OUTBOX_INTERNAL_SUBSCRIBER_WORKERS", "8"),
		OutboxInternalBusBuffer:             getenv("OUTBOX_INTERNAL_BUS_BUFFER", "1024"),
		OutboxInternalSubscriberBatchSize:   getenv("OUTBOX_INTERNAL_SUBSCRIBER_BATCH_SIZE", "1"),
		OutboxInternalSubscriberBatchWaitMs: getenv("OUTBOX_INTERNAL_SUBSCRIBER_BATCH_WAIT_MS", "0"),
		OutboxRelayParallelKeys:             getenv("OUTBOX_RELAY_PARALLEL_KEYS", "8"),
		OutboxESCheckpointShards:            getenv("OUTBOX_ES_CHECKPOINT_SHARDS", "16"),
		OutboxESCheckpointIdleAfterSec:      getenv("OUTBOX_ES_CHECKPOINT_IDLE_AFTER_SEC", "300"),

		AdminToken:                getenv("ADMIN_TOKEN", ""),
		FacetEngine:               getenv("DBK_FACET_ENGINE", "auto"),
		OpenLineageEmitterEnabled: getenv("OPENLINEAGE_EMITTER_ENABLED", ""),
		OpenLineageEndpoint:       getenv("OPENLINEAGE_ENDPOINT", ""),
		OpenLineageSubscription:   getenv("OPENLINEAGE_SUBSCRIPTION", ""),
		OpenLineageNamespace:      getenv("OPENLINEAGE_NAMESPACE", ""),
		OpenLineageProducer:       getenv("OPENLINEAGE_PRODUCER", ""),
		OpenLineageTimeoutMs:      getenv("OPENLINEAGE_TIMEOUT_MS", ""),
		ArgoWorkflowsNamespace:    getenv("ARGO_WORKFLOWS_NAMESPACE", "argo"),
		BatchDispatchMode:         getenv("BATCH_DISPATCH_MODE", "submitter"),
		RuntimeConfigTTLDays:      getenvInt32("RUNTIME_CONFIG_TTL_DAYS", 35),
		ArgoWorkflowTTLSecondsAfterCompletion: getenvInt32(
			"ARGO_WORKFLOW_TTL_SECONDS_AFTER_COMPLETION",
			transpiler.DefaultTTLSecondsAfterCompletion,
		),
		PipelineResourceMaxCPU:                getenv("PIPELINE_RESOURCE_MAX_CPU", ""),
		PipelineResourceMaxMemory:             getenv("PIPELINE_RESOURCE_MAX_MEMORY", ""),
		PipelineResourceMaxDisk:               getenv("PIPELINE_RESOURCE_MAX_DISK", ""),
		PipelineResourceMaxGPU:                getenv("PIPELINE_RESOURCE_MAX_GPU", ""),
		PipelineUnschedulablePendingThreshold: getenv("PIPELINE_UNSCHEDULABLE_PENDING_THRESHOLD", "15m"),

		ArgoExitHookEnabled:           strings.EqualFold(getenv("ARGO_EXIT_HOOK_ENABLED", "false"), "true"),
		ArgoRunWebhookURL:             getenv("ARGO_RUN_WEBHOOK_URL", ""),
		ArgoRunWebhookToken:           getenv("ARGO_RUN_WEBHOOK_TOKEN", ""),
		ArgoRunWebhookTokenSecretName: getenv("ARGO_RUN_WEBHOOK_TOKEN_SECRET_NAME", "databrew-run-webhook-token"),
		ArgoRunWebhookTokenSecretKey:  getenv("ARGO_RUN_WEBHOOK_TOKEN_SECRET_KEY", "token"),
		ArgoRunWebhookImage:           getenv("ARGO_RUN_WEBHOOK_IMAGE", "curlimages/curl:8.11.1"),

		BackfillNotifyFeishuWebhookURL: getenv("BACKFILL_NOTIFY_FEISHU_WEBHOOK_URL", ""),
		FrontendBaseURL:                getenv("FRONTEND_BASE_URL", ""),

		PipelineRunWatcherIntervalSec: getenvInt32("PIPELINE_RUN_WATCHER_INTERVAL_SEC", 30),
		PipelineRunWatcherScanLimit:   getenvInt32("PIPELINE_RUN_WATCHER_SCAN_LIMIT", 100),

		BackfillReconcileIntervalSec: getenvInt32("BACKFILL_RECONCILE_INTERVAL_SEC", 60),
		BackfillReconcileScanLimit:   getenvInt32("BACKFILL_RECONCILE_SCAN_LIMIT", 200),

		PricingConfigPath: getenv("PRICING_CONFIG_PATH", ""),

		GraceAPIURL:                  getenv("GRACE_API_URL", ""),
		GraceUsername:                getenv("GRACE_USERNAME", ""),
		GracePassword:                getenv("GRACE_PASSWORD", ""),
		VideoDurationSyncIntervalSec: getenvInt32("VIDEO_DURATION_SYNC_INTERVAL_SEC", 600),
	}
}

func (c *Config) PipelineUnschedulablePendingThresholdDuration() time.Duration {
	if c == nil {
		return 15 * time.Minute
	}
	d, err := time.ParseDuration(c.PipelineUnschedulablePendingThreshold)
	if err != nil || d < 0 {
		return 15 * time.Minute
	}
	return d
}

// AdminRoutesEnabled reports whether privileged admin/internal HTTP routes are mounted.
// In production, ADMIN_TOKEN must be set; dev may fall back to GRACE_TOKEN when unset.
func (c *Config) AdminRoutesEnabled() bool {
	if c.AdminToken != "" {
		return true
	}
	return c.Env != "production"
}

// devDefaultDatabrewToken and devDefaultJWTSecret mirror the fallback values
// in Load(). Kept as named constants (not re-reading getenv) so Validate
// checks the exact strings a dev/local deployment would end up with if the
// corresponding env var were left unset.
const (
	devDefaultDatabrewToken = "dev-token"
	devDefaultJWTSecret     = "dev-jwt-secret" // pragma: allowlist secret
)

// Validate fails fast when a production deployment is about to run with
// dev-only defaults. Load() intentionally falls back to dev-token /
// dev-jwt-secret so local/dev environments work with zero configuration;
// the same fallback reaching a production process means DATABREW_TOKEN or
// JWT_SECRET was never set, which would otherwise silently accept the
// well-known dev credential in prod. Call this once at startup — non-nil
// error means the process must not serve traffic.
func (c *Config) Validate() error {
	if c == nil {
		return errors.New("config: nil")
	}
	if c.Env != "production" {
		return nil
	}
	var errs []error
	if c.DatabrewToken == "" || c.DatabrewToken == devDefaultDatabrewToken {
		errs = append(errs, fmt.Errorf("DATABREW_TOKEN must be set to a non-default value in production (got %q)", c.DatabrewToken))
	}
	if c.JWTSecret == "" || c.JWTSecret == devDefaultJWTSecret { // pragma: allowlist secret
		errs = append(errs, fmt.Errorf("JWT_SECRET must be set to a non-default value in production (got %q)", c.JWTSecret))
	}
	// ADMIN_TOKEN is intentionally NOT validated here: AdminRoutesEnabled()
	// already treats an unset token as "admin routes disabled" (a safe
	// degraded state), and infra.go logs a warning for it. Failing startup
	// here would turn an intentional safe-default into a hard outage.
	return errors.Join(errs...)
}

func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// splitCSVLower splits a comma-separated list, trimming + lowercasing each
// non-empty element. Returns nil for empty input.
func splitCSVLower(s string) []string {
	if strings.TrimSpace(s) == "" {
		return nil
	}
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if v := strings.ToLower(strings.TrimSpace(p)); v != "" {
			out = append(out, v)
		}
	}
	return out
}

// IsAdminEmail reports whether an email is in the admin allowlist (ADMIN_EMAILS).
func (c *Config) IsAdminEmail(email string) bool {
	e := strings.ToLower(strings.TrimSpace(email))
	for _, a := range c.AdminEmails {
		if a == e {
			return true
		}
	}
	return false
}

func getenvInt32(key string, fallback int32) int32 {
	raw := os.Getenv(key)
	if raw == "" {
		return fallback
	}
	n, err := strconv.ParseInt(raw, 10, 32)
	if err != nil || n < 0 {
		return fallback
	}
	return int32(n)
}
