package config

import (
	"os"

	"github.com/joho/godotenv"
)

type Config struct {
	Env             string
	Port            string
	McapGatewayPort string
	DeliveryPort    string

	// Storage backend: postgres (default)
	StorageBackend string

	// PostgreSQL
	DBHost     string
	DBPort     string
	DBUser     string
	DBPassword string
	DBName     string

	// GCS (optional, for future derived artifacts)
	GCSProject       string
	GCSDerivedBucket string

	// Pub/Sub
	PubSubProject      string
	TopicMcapFinalized string
	TopicAssetEvents   string

	// Auth (Phase 0 static token; Phase 0.5 → OIDC)
	GraceToken string

	// Logging
	LogLevel  string // debug, info, warn, error
	LogFormat string // text, json
	LogFile   string // file path (empty = stdout only)

	// Rate Limiting (per IP)
	RateLimitRPS   string // requests per second (0 = disabled)
	RateLimitBurst string // burst size (default = RPS * 2)

	// Circuit Breaker
	CBEnabled     string // "true" to enable
	CBWindowSec   string // sliding window seconds (default: 60)
	CBThreshold   string // error count to trip (default: 10)
	CBCooldownSec string // cooldown seconds (default: 30)

	// Local lakehouse MVP report generated by deploy/local/iceberg/notebooks/build_lakehouse_mvp.py.
	LakehouseReportPath string

	// Lakehouse analytical query layer.
	//
	// LakehouseBackend selects the engine: "bigquery" (default) reads
	// BigLake-managed Iceberg via BigQuery external tables; "none" disables
	// the layer entirely. Trino is no longer supported — see
	// docs/adr/001-iceberg-catalog-selection.md.
	LakehouseBackend   string
	LakehouseBQProject string // GCP project hosting the BigQuery dataset
	LakehouseBQDataset string // dataset containing Iceberg external tables (e.g. lakehouse_bronze)

	// Elasticsearch
	ElasticsearchURL      string
	ElasticsearchUsername string // optional; defaults to "elastic" when ElasticsearchPassword is set
	ElasticsearchPassword string // optional; HTTP Basic auth to ES when non-empty

	// Outbox relay (PG asset_events → Pub/Sub) and ES subscriber (Pub/Sub → Elasticsearch).
	OutboxRelayEnabled        string
	OutboxRelayBatchSize      string
	OutboxRelayIntervalMs     string
	OutboxRelaySafetyLagSec   string
	OutboxRelayLeaseSec       string
	OutboxRelayMaxRetries     string
	OutboxProgressLogInterval string // seconds; 0 disables periodic relay progress logs
	OutboxESSubscriberEnabled string
	OutboxESSubscription      string // subscription id in PubSubProject (short name)
	OutboxTransport           string // internal | pubsub | kafka (default internal)
	OutboxKafkaBrokers        string // comma-separated brokers for kafka mode
	OutboxKafkaTopic          string // topic for kafka mode (fallback: TOPIC_ASSET_EVENTS)
	OutboxKafkaGroupID        string // consumer group for ES subscriber in kafka mode

	// OUTBOX_TRANSPORT=internal only: parallel ES handlers (per routing key serial).
	OutboxInternalSubscriberWorkers string
	// OUTBOX_TRANSPORT=internal only: in-memory bus channel buffer (matches the
	// historical NewInMemoryBus(1024) constant). Larger buffers absorb relay
	// bursts without back-pressuring the publisher.
	OutboxInternalBusBuffer string
	// OUTBOX_TRANSPORT=internal only: maximum events coalesced into a single ES
	// _bulk request per worker. 1 disables batching (legacy single-doc path).
	OutboxInternalSubscriberBatchSize string
	// OUTBOX_TRANSPORT=internal only: how long a worker is allowed to wait after
	// the first message arrives before flushing a partial batch. 0 means
	// "flush whatever is already in the channel without waiting".
	OutboxInternalSubscriberBatchWaitMs string
	// Max concurrent ordering-key groups in one relay flush (different keys run in parallel).
	OutboxRelayParallelKeys string

	// OutboxESCheckpointShards is the modulus for the es_sync_checkpoint table.
	// Each successful ES bulk emits at most "shards-in-batch" UPSERTs into this
	// table; the cross-shard MIN(applied_seq) is exposed as consumer_lag in
	// /api/v1/search/sync-progress. Larger values give finer-grained MIN
	// (less stale-shard drag) at the cost of more rows; 16 is a reasonable
	// default. Must be <= 1024.
	OutboxESCheckpointShards string

	// OutboxESCheckpointIdleAfterSec treats a checkpoint row as "caught up" for
	// MIN(applied_seq) purposes when its updated_at is older than this many
	// seconds. Without this, a low-traffic shard whose applied_seq legitimately
	// lags PG's max would drag consumer_lag up forever. 0 disables (legacy
	// behavior: raw MIN over all rows). 300s (5 min) matches a typical relay
	// poll cycle + ES bulk window.
	OutboxESCheckpointIdleAfterSec string

	// Admin endpoints (search reindex, etc.). Empty disables routes.
	AdminToken string
}

func Load() *Config {
	// Optional explicit env file for runtime config aggregation.
	// This is useful in Cloud Run / CI when operators want a single config file
	// (PG/ES/Trino/etc.) without relying on a local .env in cwd.
	if envFile := os.Getenv("BACKEND_ENV_FILE"); envFile != "" {
		_ = godotenv.Overload(envFile)
	}

	return &Config{
		Env:             getenv("ENV", "development"),
		Port:            getenv("PORT", "8080"),
		McapGatewayPort: getenv("MCAP_GATEWAY_PORT", "8081"),
		DeliveryPort:    getenv("DELIVERY_PORT", "8082"),
		StorageBackend:  getenv("STORAGE_BACKEND", "postgres"),

		DBHost:     getenv("DB_HOST", "localhost"),
		DBPort:     getenv("DB_PORT", "5432"),
		DBUser:     getenv("DB_USER", "postgres"),
		DBPassword: getenv("DB_PASSWORD", "postgres"),
		DBName:     getenv("DB_NAME", "cyber_databrew_dev"),

		GCSProject:       getenv("GCS_PROJECT", ""),
		GCSDerivedBucket: getenv("GCS_DERIVED_BUCKET", "grace-derived"),

		PubSubProject:      getenv("PUBSUB_PROJECT", ""),
		TopicMcapFinalized: getenv("TOPIC_MCAP_FINALIZED", "gcs.mcap.finalized.v1"),
		TopicAssetEvents:   getenv("TOPIC_ASSET_EVENTS", "cyber-databrew-asset-events"),

		GraceToken: getenv("GRACE_TOKEN", "dev-token"),

		LogLevel:  getenv("LOG_LEVEL", "info"),
		LogFormat: getenv("LOG_FORMAT", "text"),
		LogFile:   getenv("LOG_FILE", ""),

		RateLimitRPS:   getenv("RATE_LIMIT_RPS", "0"),
		RateLimitBurst: getenv("RATE_LIMIT_BURST", "0"),

		CBEnabled:     getenv("CB_ENABLED", "false"),
		CBWindowSec:   getenv("CB_WINDOW_SEC", "60"),
		CBThreshold:   getenv("CB_THRESHOLD", "10"),
		CBCooldownSec: getenv("CB_COOLDOWN_SEC", "30"),

		LakehouseReportPath: getenv("LAKEHOUSE_REPORT_PATH", "../deploy/local/iceberg/notebooks/lakehouse_report.json"),

		LakehouseBackend:   getenv("LAKEHOUSE_BACKEND", "bigquery"),
		LakehouseBQProject: getenv("LAKEHOUSE_BQ_PROJECT", getenv("GCS_PROJECT", "")),
		LakehouseBQDataset: getenv("LAKEHOUSE_BQ_DATASET", "lakehouse_bronze"),

		ElasticsearchURL:      getenv("ELASTICSEARCH_URL", "http://localhost:9200"),
		ElasticsearchUsername: getenv("ELASTICSEARCH_USERNAME", ""),
		ElasticsearchPassword: getenv("ELASTICSEARCH_PASSWORD", ""),

		OutboxRelayEnabled:        getenv("OUTBOX_RELAY_ENABLED", "false"),
		OutboxRelayBatchSize:      getenv("OUTBOX_RELAY_BATCH_SIZE", "200"),
		OutboxRelayIntervalMs:     getenv("OUTBOX_RELAY_INTERVAL_MS", "500"),
		OutboxRelaySafetyLagSec:   getenv("OUTBOX_RELAY_SAFETY_LAG_SEC", "2"),
		OutboxRelayLeaseSec:       getenv("OUTBOX_RELAY_LEASE_SEC", "30"),
		OutboxRelayMaxRetries:     getenv("OUTBOX_RELAY_MAX_RETRIES", "20"),
		OutboxProgressLogInterval: getenv("OUTBOX_PROGRESS_LOG_INTERVAL_SEC", "60"),
		OutboxESSubscriberEnabled: getenv("OUTBOX_ES_SUBSCRIBER_ENABLED", "false"),
		OutboxESSubscription:      getenv("OUTBOX_ES_SUBSCRIPTION", ""),
		OutboxTransport:           getenv("OUTBOX_TRANSPORT", "internal"),
		OutboxKafkaBrokers:        getenv("OUTBOX_KAFKA_BROKERS", ""),
		OutboxKafkaTopic:          getenv("OUTBOX_KAFKA_TOPIC", ""),
		OutboxKafkaGroupID:        getenv("OUTBOX_KAFKA_GROUP_ID", "cyber-databrew-outbox-es"),

		OutboxInternalSubscriberWorkers:     getenv("OUTBOX_INTERNAL_SUBSCRIBER_WORKERS", "8"),
		OutboxInternalBusBuffer:             getenv("OUTBOX_INTERNAL_BUS_BUFFER", "1024"),
		OutboxInternalSubscriberBatchSize:   getenv("OUTBOX_INTERNAL_SUBSCRIBER_BATCH_SIZE", "1"),
		OutboxInternalSubscriberBatchWaitMs: getenv("OUTBOX_INTERNAL_SUBSCRIBER_BATCH_WAIT_MS", "0"),
		OutboxRelayParallelKeys:             getenv("OUTBOX_RELAY_PARALLEL_KEYS", "8"),
		OutboxESCheckpointShards:            getenv("OUTBOX_ES_CHECKPOINT_SHARDS", "16"),
		OutboxESCheckpointIdleAfterSec:      getenv("OUTBOX_ES_CHECKPOINT_IDLE_AFTER_SEC", "300"),

		AdminToken: getenv("ADMIN_TOKEN", ""),
	}
}

func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
