package config

import "os"

type Config struct {
	Env             string
	Port            string
	McapGatewayPort string
	DeliveryPort    string

	// Storage backend: bigtable | postgres
	StorageBackend string

	// Bigtable
	BigtableProject  string
	BigtableInstance string

	// PostgreSQL
	DBHost     string
	DBPort     string
	DBUser     string
	DBPassword string
	DBName     string

	// GCS (optional, for future derived artifacts)
	GCSProject       string
	GCSDerivedBucket string

	// Pub/Sub
	PubSubProject      string
	TopicMcapFinalized string
	TopicAssetEvents   string

	// Auth (Phase 0 static token; Phase 0.5 → OIDC)
	GraceToken string

	// Logging
	LogLevel  string // debug, info, warn, error
	LogFormat string // text, json
	LogFile   string // file path (empty = stdout only)

	// Rate Limiting (per IP)
	RateLimitRPS   string // requests per second (0 = disabled)
	RateLimitBurst string // burst size (default = RPS * 2)

	// Circuit Breaker
	CBEnabled     string // "true" to enable
	CBWindowSec   string // sliding window seconds (default: 60)
	CBThreshold   string // error count to trip (default: 10)
	CBCooldownSec string // cooldown seconds (default: 30)

	// Local lakehouse MVP report generated by deploy/local/iceberg/notebooks/build_lakehouse_mvp.py.
	LakehouseReportPath string

	// Trino analytical query layer for Iceberg.
	TrinoEnabled string
	TrinoURL     string
	TrinoCatalog string
	TrinoSchema  string

	// Elasticsearch
	ElasticsearchURL string

	// CDC / WAL-driven sync (long-term architecture skeleton).
	CDCEnabled              string
	CDCSourceDriver         string
	CDCKafkaBrokers         string
	CDCKafkaGroupID         string
	CDCKafkaPollTimeoutMs   string
	CDCKafkaMaxBatch        string
	CDCAssetEventsTopic     string
	CDCAssetsTopic          string
	CDCAssetTagsTopic       string
	CDCAssetAlgoLatestTopic string
	CDCMcapFilesTopic       string
	CDCBronzeStagingDir     string

	// Outbox worker (in-process ES sink).
	OutboxWorkerEnabled      string
	OutboxWorkerTickSec      string
	OutboxWorkerBatch        string
	OutboxWorkerRetryLimit   string
	OutboxWorkerFatalOnPanic string

	// Admin endpoints (search reindex, etc.). Empty disables routes.
	AdminToken string
}

func Load() *Config {
	return &Config{
		Env:             getenv("ENV", "development"),
		Port:            getenv("PORT", "8080"),
		McapGatewayPort: getenv("MCAP_GATEWAY_PORT", "8081"),
		DeliveryPort:    getenv("DELIVERY_PORT", "8082"),
		StorageBackend:  getenv("STORAGE_BACKEND", "postgres"),

		BigtableProject:  getenv("BIGTABLE_PROJECT", ""),
		BigtableInstance: getenv("BIGTABLE_INSTANCE", "poc-datainfra"),

		DBHost:     getenv("DB_HOST", "localhost"),
		DBPort:     getenv("DB_PORT", "5432"),
		DBUser:     getenv("DB_USER", "postgres"),
		DBPassword: getenv("DB_PASSWORD", "postgres"),
		DBName:     getenv("DB_NAME", "data4cyber"),

		GCSProject:       getenv("GCS_PROJECT", ""),
		GCSDerivedBucket: getenv("GCS_DERIVED_BUCKET", "grace-derived"),

		PubSubProject:      getenv("PUBSUB_PROJECT", ""),
		TopicMcapFinalized: getenv("TOPIC_MCAP_FINALIZED", "gcs.mcap.finalized.v1"),
		TopicAssetEvents:   getenv("TOPIC_ASSET_EVENTS", "grace-asset-events"),

		GraceToken: getenv("GRACE_TOKEN", "dev-token"),

		LogLevel:  getenv("LOG_LEVEL", "info"),
		LogFormat: getenv("LOG_FORMAT", "text"),
		LogFile:   getenv("LOG_FILE", ""),

		RateLimitRPS:   getenv("RATE_LIMIT_RPS", "0"),
		RateLimitBurst: getenv("RATE_LIMIT_BURST", "0"),

		CBEnabled:     getenv("CB_ENABLED", "false"),
		CBWindowSec:   getenv("CB_WINDOW_SEC", "60"),
		CBThreshold:   getenv("CB_THRESHOLD", "10"),
		CBCooldownSec: getenv("CB_COOLDOWN_SEC", "30"),

		LakehouseReportPath: getenv("LAKEHOUSE_REPORT_PATH", "../deploy/local/iceberg/notebooks/lakehouse_report.json"),

		TrinoEnabled: getenv("TRINO_ENABLED", "true"),
		TrinoURL:     getenv("TRINO_URL", "http://data-platform@localhost:8082"),
		TrinoCatalog: getenv("TRINO_CATALOG", "iceberg"),
		TrinoSchema:  getenv("TRINO_SCHEMA", "robot"),

		ElasticsearchURL: getenv("ELASTICSEARCH_URL", "http://localhost:9200"),

		CDCEnabled:              getenv("CDC_ENABLED", "false"),
		CDCSourceDriver:         getenv("CDC_SOURCE_DRIVER", ""),
		CDCKafkaBrokers:         getenv("CDC_KAFKA_BROKERS", "localhost:19092"),
		CDCKafkaGroupID:         getenv("CDC_KAFKA_GROUP_ID", "data-platform-cdc"),
		CDCKafkaPollTimeoutMs:   getenv("CDC_KAFKA_POLL_TIMEOUT_MS", "1000"),
		CDCKafkaMaxBatch:        getenv("CDC_KAFKA_MAX_BATCH", "100"),
		CDCAssetEventsTopic:     getenv("CDC_TOPIC_ASSET_EVENTS", "asset_events"),
		CDCAssetsTopic:          getenv("CDC_TOPIC_ASSETS", "assets"),
		CDCAssetTagsTopic:       getenv("CDC_TOPIC_ASSET_TAGS", "asset_tags"),
		CDCAssetAlgoLatestTopic: getenv("CDC_TOPIC_ASSET_ALGO_LATEST", "asset_algo_latest"),
		CDCMcapFilesTopic:       getenv("CDC_TOPIC_MCAP_FILES", "mcap_files"),
		CDCBronzeStagingDir:     getenv("CDC_BRONZE_STAGING_DIR", "/tmp/iceberg-staging"),

		OutboxWorkerEnabled:      getenv("OUTBOX_WORKER_ENABLED", "false"),
		OutboxWorkerTickSec:      getenv("OUTBOX_WORKER_TICK_SEC", "30"),
		OutboxWorkerBatch:        getenv("OUTBOX_WORKER_BATCH", "100"),
		OutboxWorkerRetryLimit:   getenv("OUTBOX_WORKER_RETRY_LIMIT", "10"),
		OutboxWorkerFatalOnPanic: getenv("OUTBOX_WORKER_FATAL_ON_PANIC", "false"),

		AdminToken: getenv("ADMIN_TOKEN", ""),
	}
}

func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
